In [1]:
library(rvest)
library(polite)
library(tidyverse)
library(ggplot2)
library(scales)
library(dplyr)
library(forcats)
library(magrittr)
library(readr)
library(stringr)
library(lubridate)
library(purrr)
library(readxl)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.7
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()         masks stats::filter()
✖ readr::guess_encoding() masks rvest::guess_encoding()
✖ dplyr::lag()            masks stats::lag()


Attaching package: ‘scales’


The following object is masked from ‘package:purrr’:

    discard


The following object is masked from ‘package:readr’:

    col_factor



Attaching package: ‘magrittr’


The following object is masked from ‘package:purrr’:

    set_names


The following object is masked from ‘package:tidyr’:

    extract



Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

In [2]:
URL1 <- 'https://www.nfl.com/standings/league/2021/REG'
HTML_DOC1 <- rvest::read_html(x = URL1)
NFL_2021 <- HTML_DOC1 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL2 <- 'https://www.nfl.com/standings/league/2020/REG'
HTML_DOC2 <- rvest::read_html(x = URL2)
NFL_2020 <- HTML_DOC2 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL3 <- 'https://www.nfl.com/standings/league/2019/REG'
HTML_DOC3 <- rvest::read_html(x = URL3)
NFL_2019 <- HTML_DOC3 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL4 <- 'https://www.nfl.com/standings/league/2018/REG'
HTML_DOC4 <- rvest::read_html(x = URL4)
NFL_2018 <- HTML_DOC4 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL5 <- 'https://www.nfl.com/standings/league/2017/REG'
HTML_DOC5 <- rvest::read_html(x = URL5)
NFL_2017 <- HTML_DOC5 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL6 <- 'https://www.nfl.com/standings/league/2016/REG'
HTML_DOC6 <- rvest::read_html(x = URL6)
NFL_2016 <- HTML_DOC6 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL7 <- 'https://www.nfl.com/standings/league/2015/REG'
HTML_DOC7 <- rvest::read_html(x = URL7)
NFL_2015 <- HTML_DOC7 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL8 <- 'https://www.nfl.com/standings/league/2014/REG'
HTML_DOC8 <- rvest::read_html(x = URL8)
NFL_2014 <- HTML_DOC8 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL9 <- 'https://www.nfl.com/standings/league/2013/REG'
HTML_DOC9 <- rvest::read_html(x = URL9)
NFL_2013 <- HTML_DOC9 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL10 <- 'https://www.nfl.com/standings/league/2012/REG'
HTML_DOC10 <- rvest::read_html(x = URL10)
NFL_2012 <- HTML_DOC1 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL_curr <- 'https://www.nfl.com/standings/league/2022/REG'
HTML_DOC_curr <- rvest::read_html(x = URL_curr)
NFL_2022 <- HTML_DOC_curr %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

In [35]:
NFL_2021 <- NFL_2021 %>% str_extract(string = NFL Team, pattern = '/w [A-Z][a-z]+')

ERROR: Error in parse(text = x, srcfile = src): <text>:1:51: unexpected symbol
1: NFL_2021 <- NFL_2021 %>% str_extract(string = NFL Team
                                                      ^

In [3]:
NFL_2021

[[1]]
# A tibble: 32 × 17
   `NFL Team`        W     L     T   PCT    PF    PA `Net Pts` Home  Road  Div
   <chr>         <int> <int> <int> <dbl> <int> <int>     <int> <chr> <chr> <chr>
 1 Detroit Lion…     3    13     1 0.206   325   467      -142 3 - … 0 - … 2 - …
 2 Jacksonville…     3    14     0 0.176   253   457      -204 3 - … 0 - … 1 - …
 3 Houston Texa…     4    13     0 0.235   280   452      -172 2 - … 2 - … 3 - …
 4 New York Gia…     4    13     0 0.235   258   416      -158 3 - … 1 - … 1 - …
 5 New York Jet…     4    13     0 0.235   310   504      -194 3 - … 1 - … 0 - …
 6 Carolina Pan…     5    12     0 0.294   304   404      -100 2 - … 3 - … 2 - …
 7 Chicago Bear…     6    11     0 0.353   311   407       -96 3 - … 3 - … 2 - …
 8 Atlanta Falc…     7    10     0 0.412   313   459      -146 2 - … 5 - … 2 - …
 9 Denver Bronc…     7    10     0 0.412   335   322        13 4 - … 3 - … 1 - …
10 Seattle Seah…     7    10     0 0.412   395   366        29 3 - … 4 - … 3 - …
# … with 22 more rows, and 6 more variables: Pct <dbl>, Conf <chr>, Pct <dbl>,
#   `Non-Conf` <chr>, Strk <chr>, `Last 5` <chr>

In [69]:
URL1_nba <- 'https://www.covers.com/sport/basketball/nba/standings'
HTML_DOC1_nba <- rvest::read_html(x = URL1_nba)
NBA_2022 <- HTML_DOC1_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL2_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2021-2022'
HTML_DOC2_nba <- rvest::read_html(x = URL2_nba)
NBA_2021 <- HTML_DOC2_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL3_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2020-2021'
HTML_DOC3_nba <- rvest::read_html(x = URL3_nba)
NBA_2020 <- HTML_DOC3_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL4_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2019-2020'
HTML_DOC4_nba <- rvest::read_html(x = URL4_nba)
NBA_2019 <- HTML_DOC4_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL5_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2018-2019'
HTML_DOC5_nba <- rvest::read_html(x = URL5_nba)
NBA_2018 <- HTML_DOC5_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL6_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2017-2018'
HTML_DOC6_nba <- rvest::read_html(x = URL6_nba)
NBA_2017 <- HTML_DOC6_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL7_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2016-2017'
HTML_DOC7_nba <- rvest::read_html(x = URL7_nba)
NBA_2016 <- HTML_DOC7_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL8_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2015-2016'
HTML_DOC8_nba <- rvest::read_html(x = URL8_nba)
NBA_2015 <- HTML_DOC8_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL9_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2014-2015'
HTML_DOC9_nba <- rvest::read_html(x = URL9_nba)
NBA_2014 <- HTML_DOC9_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL10_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2013-2014'
HTML_DOC10_nba <- rvest::read_html(x = URL10_nba)
NBA_2013 <- HTML_DOC10_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL11_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2012-2013'
HTML_DOC11_nba <- rvest::read_html(x = URL11_nba)
NBA_2012 <- HTML_DOC11_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

In [64]:
NBA_2022 <- as.data.frame(NBA_2022)
NBA_2022_standings <- NBA_2022 %>% filter(row(NBA_2022) > 74) 
NBA_2022_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4,
                             Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)

   Team
1  L.A. Lakers\r\n                                    \r\n                                    \r\n                                        LAL
2  L.A. Clippers\r\n                                    \r\n                                    \r\n                                        LAC
3  Golden State\r\n                                    \r\n                                    \r\n                                        GS
4  Sacramento\r\n                                    \r\n                                    \r\n                                        SAC
5  Phoenix\r\n                                    \r\n                                    \r\n                                        PHO
6  Memphis\r\n                                    \r\n                                    \r\n                                        MEM
7  Utah\r\n                                    \r\n                                    \r\n                                        UTA
8  Minnesota\r\n                                    \r\n                                    \r\n                                        MIN
9  Milwaukee\r\n                                    \r\n                                    \r\n                                        MIL
10 Houston\r\n                                    \r\n                                    \r\n                                        HOU
11 Portland\r\n                                    \r\n                                    \r\n                                        POR
12 Oklahoma City\r\n                                    \r\n                                    \r\n                                        OKC
13 Atlanta\r\n                                    \r\n                                    \r\n                                        ATL
14 Detroit\r\n                                    \r\n                                    \r\n                                        DET
15 San Antonio\r\n                                    \r\n                                    \r\n                                        SA
16 New Orleans\r\n                                    \r\n                                    \r\n                                        NO
17 Miami\r\n                                    \r\n                                    \r\n                                        MIA
18 Indiana\r\n                                    \r\n                                    \r\n                                        IND
19 Dallas\r\n                                    \r\n                                    \r\n                                        DAL
20 Washington\r\n                                    \r\n                                    \r\n                                        WAS
21 Denver\r\n                                    \r\n                                    \r\n                                        DEN
22 Charlotte\r\n                                    \r\n                                    \r\n                                        CHA
23 Orlando\r\n                                    \r\n                                    \r\n                                        ORL
24 Chicago\r\n                                    \r\n                                    \r\n                                        CHI
25 Cleveland\r\n                                    \r\n                                    \r\n                                        CLE
26 New York\r\n                                    \r\n                                    \r\n                                        NY
27 Boston\r\n                                    \r\n                                    \r\n                                        BOS
28 Toronto\r\n                                    \r\n                                    \r\n                                        TOR
29 Philadelphia\r\n                                    \r\n                                    \r\n                                        PHI
30 Brooklyn\r\n                                    \r\n                                    \r\n                                        BK
   Wins Losses Percentage Home Away Var.7 Var.8 Var.9 Var.10 Var.11 Var.12
1  2    8      .200       2-7  0-2  2-4   0-4   2-8-0 5-5-0  NA     NA
2  6    5      .545       5-5  2-1  2-3   4-2   4-7-0 2-9-0  NA     NA
3  4    7      .364       3-3  3-1  4-1   0-6   3-8-0 7-3-1  NA     NA
4  3    6      .333       0-5  0-3  1-3   2-3   6-3-0 3-6-0  NA     NA
5  7    3      .700       7-2  2-0  6-1   1-2   6-4-0 3-7-0  NA     NA
6  7    4      .636       3-3  1-1  4-1   3-3   4-7-0 6-5-0  NA     NA
7  9    3      .750       9-3  2-1  5-0   4-3   9-3-0 5-7-0  NA     NA
8  5    6      .455       5-4  2-1  4-4   1-2   4-7-0 3-8-0  NA     NA
9  9    1      .900       6-1  2-0  7-0   2-1   8-2-0 3-7-0  NA     NA
10 2    9      .182       1-7  0-1  1-2   1-7   6-5-0 6-5-0  NA     NA
11 7    3      .700       6-2  1-0  3-2   4-1   8-2-0 3-7-0  NA     NA
12 4    6      .400       3-4  0-4  3-2   1-4   6-4-0 5-5-0  NA     NA
13 7    3      .700       5-3  1-1  4-1   3-2   5-5-0 6-4-0  NA     NA
14 3    8      .273       1-8  0-4  3-3   0-5   5-6-0 6-5-0  NA     NA
15 5    6      .455       2-4  0-0  2-4   3-2   6-5-0 5-6-0  NA     NA
16 5    5      .500       3-3  1-0  2-1   3-4   4-6-0 8-2-0  NA     NA
17 4    7      .364       1-4  0-0  3-4   1-3   2-9-0 5-6-0  NA     NA
18 5    5      .500       4-4  1-1  3-2   2-3   6-4-0 5-5-0  NA     NA
19 6    3      .667       2-3  1-1  5-1   1-2   3-5-1 6-3-0  NA     NA
20 5    6      .455       5-5  1-0  2-3   3-3   5-5-1 4-7-0  NA     NA
21 7    3      .700       7-3  3-2  4-0   3-3   5-5-0 5-5-0  NA     NA
22 3    8      .273       1-5  1-2  1-4   2-4   4-6-1 5-5-1  NA     NA
23 2    9      .182       1-5  1-1  2-3   0-6   4-6-1 7-4-0  NA     NA
24 6    6      .500       6-5  1-1  4-2   2-4   7-4-1 5-7-0  NA     NA
25 8    2      .800       7-1  2-0  4-0   4-2   8-2-0 6-4-0  NA     NA
26 5    5      .500       4-4  1-1  3-2   2-3   5-5-0 6-4-0  NA     NA
27 7    3      .700       6-3  2-0  3-1   4-2   4-6-0 6-4-0  NA     NA
28 6    5      .545       5-4  1-2  4-1   2-4   8-3-0 5-6-0  NA     NA
29 5    6      .455       4-5  1-3  2-4   3-2   5-6-0 5-6-0  NA     NA
30 4    7      .364       4-3  1-0  2-4   2-3   3-7-1 4-7-0  NA     NA
   Var.13 Var.14
1  NA     NA
2  NA     NA
3  NA     NA
4  NA     NA
5  NA     NA
6  NA     NA
7  NA     NA
8  NA     NA
9  NA     NA
10 NA     NA
11 NA     NA
12 NA     NA
13 NA     NA
14 NA     NA
15 NA     NA
16 NA     NA
17 NA     NA
18 NA     NA
19 NA     NA
20 NA     NA
21 NA     NA
22 NA     NA
23 NA     NA
24 NA     NA
25 NA     NA
26 NA     NA
27 NA     NA
28 NA     NA
29 NA     NA
30 NA     NA

Rows: 30
Columns: 14
$ Eastern.Conference <chr> "L.A. Lakers\r\n                                   …
$ Var.2              <chr> "2", "6", "4", "3", "7", "7", "9", "5", "9", "2", "…
$ Var.3              <chr> "8", "5", "7", "6", "3", "4", "3", "6", "1", "9", "…
$ Var.4              <chr> ".200", ".545", ".364", ".333", ".700", ".636", ".7…
$ Var.5              <chr> "2-7", "5-5", "3-3", "0-5", "7-2", "3-3", "9-3", "5…
$ Var.6              <chr> "0-2", "2-1", "3-1", "0-3", "2-0", "1-1", "2-1", "2…
$ Var.7              <chr> "2-4", "2-3", "4-1", "1-3", "6-1", "4-1", "5-0", "4…
$ Var.8              <chr> "0-4", "4-2", "0-6", "2-3", "1-2", "3-3", "4-3", "1…
$ Var.9              <chr> "2-8-0", "4-7-0", "3-8-0", "6-3-0", "6-4-0", "4-7-0…
$ Var.10             <chr> "5-5-0", "2-9-0", "7-3-1", "3-6-0", "3-7-0", "6-5-0…
$ Var.11             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ Var.12             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ Var.13             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ Var.14             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…

In [145]:
NBA_2022 <- as.data.frame(NBA_2022)
NBA_2022_standings <- NBA_2022 %>% filter(row(NBA_2022) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2022_stand <- NBA_2022_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2022_stand <- NBA_2022_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2022_stand <- NBA_2022_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2022_stand <- NBA_2022_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2022_stand <- NBA_2022_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2021 <- as.data.frame(NBA_2021)
NBA_2021_standings <- NBA_2021 %>% filter(row(NBA_2021) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2021_stand <- NBA_2021_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2021_stand <- NBA_2021_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2021_stand <- NBA_2021_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2021_stand <- NBA_2021_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2021_stand <- NBA_2021_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2020 <- as.data.frame(NBA_2020)
NBA_2020_standings <- NBA_2020 %>% filter(row(NBA_2020) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2020_stand <- NBA_2020_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2020_stand <- NBA_2020_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2020_stand <- NBA_2020_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2020_stand <- NBA_2020_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2020_stand <- NBA_2020_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2019 <- as.data.frame(NBA_2019)
NBA_2019_standings <- NBA_2019 %>% filter(row(NBA_2019) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2019_stand <- NBA_2019_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2019_stand <- NBA_2019_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2019_stand <- NBA_2019_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2019_stand <- NBA_2019_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2019_stand <- NBA_2019_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2018 <- as.data.frame(NBA_2018)
NBA_2018_standings <- NBA_2018 %>% filter(row(NBA_2018) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2018_stand <- NBA_2018_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2018_stand <- NBA_2018_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2018_stand <- NBA_2018_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2018_stand <- NBA_2018_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2018_stand <- NBA_2018_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2017 <- as.data.frame(NBA_2017)
NBA_2017_standings <- NBA_2017 %>% filter(row(NBA_2017) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2017_stand <- NBA_2017_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2017_stand <- NBA_2017_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2017_stand <- NBA_2017_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2017_stand <- NBA_2017_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2017_stand <- NBA_2017_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2016 <- as.data.frame(NBA_2016)
NBA_2016_standings <- NBA_2016 %>% filter(row(NBA_2016) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2016_stand <- NBA_2016_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2016_stand <- NBA_2016_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2016_stand <- NBA_2016_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2016_stand <- NBA_2016_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2016_stand <- NBA_2016_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2015 <- as.data.frame(NBA_2015)
NBA_2015_standings <- NBA_2015 %>% filter(row(NBA_2015) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2015_stand <- NBA_2015_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2015_stand <- NBA_2015_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2015_stand <- NBA_2015_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2015_stand <- NBA_2015_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2015_stand <- NBA_2015_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2014 <- as.data.frame(NBA_2014)
NBA_2014_standings <- NBA_2014 %>% filter(row(NBA_2014) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2014_stand <- NBA_2014_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2014_stand <- NBA_2014_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2014_stand <- NBA_2014_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2014_stand <- NBA_2014_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2014_stand <- NBA_2014_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2013 <- as.data.frame(NBA_2013)
NBA_2013_standings <- NBA_2013 %>% filter(row(NBA_2013) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2013_stand <- NBA_2013_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2013_stand <- NBA_2013_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2013_stand <- NBA_2013_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2013_stand <- NBA_2013_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2013_stand <- NBA_2013_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2012 <- as.data.frame(NBA_2012)
NBA_2012_standings <- NBA_2012 %>% filter(row(NBA_2012) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2012_stand <- NBA_2012_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2012_stand <- NBA_2012_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2012_stand <- NBA_2012_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9+]')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2012_stand <- NBA_2012_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2012_stand <- NBA_2012_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

In [166]:
NBA_stand <- NBA_2022_stand %>% inner_join(NBA_2021_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2020_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2019_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2018_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2017_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2016_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2015_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2014_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2013_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2012_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand

   Team          Wins Losses Home_Wins Home_Losses Away_Wins Away_Losses
1  Boston        453  356    230       148         198       208
2  Toronto       489  322    251       135         219       187
3  New York      321  483    153       221         140       262
4  Philadelphia  360  452    195       189         144       263
5  Brooklyn      373  438    184       198         165       240
6  Milwaukee     435  376    229       158         187       218
7  Cleveland     380  423    210       181         157       242
8  Chicago       380  425    193       189         165       236
9  Indiana       435  375    229       149         179       226
10 Detroit       317  488    177       209         123       279
11 Atlanta       397  408    214       166         160       242
12 Washington    383  428    208       177         155       251
13 Miami         470  342    233       140         203       202
14 Charlotte     358  446    194       192         150       254
15 Orlando       277  535    157       236         109       299
16 Utah          449  363    238       139         184       224
17 Portland      436  376    239       146         177       230
18 Denver        444  367    227       143         182       224
19 Minnesota     323  480    175       211         130       269
20 Oklahoma City 457  353    228       147         198       206
21 Phoenix       355  456    182       212         157       244
22 L.A. Clippers 507  304    253       123         225       181
23 Golden State  531  273    270       107         235       166
24 Sacramento    311  498    159       226         134       272
25 L.A. Lakers   337  472    168       210         142       262
26 Dallas        415  397    213       173         180       224
27 Memphis       436  376    220       157         187       219
28 New Orleans   353  457    190       198         148       259
29 San Antonio   502  308    255       117         215       191
30 Houston       452  359    228       148         197       211
   Conf_Wins Conf_Losses Div_Wins Div_Losses ATS_Wins ATS_Losses O_U_Wins
1  300       209          91       66        418      373        408
2  322       190         103       54        422      380        423
3  211       298          58       97        397      399        384
4  230       283          68       92        397      400        398
5  241       270          73       84        401      398        397
6  287       222          90       66        392      407        414
7  256       254          72       84        364      422        396
8  263       249          79       79        386      413        375
9  281       231          88       69        405      392        397
10 215       295          64       95        389      404        403
11 248       261          81       74        398      395        406
12 250       263          74       81        393      404        418
13 302       204          99       55        410      382        408
14 243       261          78       74        387      397        390
15 174       333          54      102        378      418        393
16 275       240          82       73        400      390        379
17 257       256          80       74        400      397        416
18 272       241          83       76        399      398        422
19 200       306          60       95        367      420        425
20 281       230          85       72        418      378        384
21 215       298          60       97        404      394        403
22 312       204         105       52        420      382        400
23 328       179         110       47        396      392        375
24 183       326          60       96        387      402        405
25 201       312          56       99        366      427        393
26 246       264          76       80        423      376        393
27 271       239          73       82        414      386        380
28 213       299          61       93        393      405        419
29 304       203          95       58        413      383        400
30 276       237          81       73        390      413        400
   O_U_Losses Games_Played Home_Played Away_Played Percentage
1  391        809          378         406         0.5599506
2  382        811          386         406         0.6029593
3  411        804          374         402         0.3992537
4  401        812          384         407         0.4433498
5  402        811          382         405         0.4599260
6  390        811          387         405         0.5363748
7  398        803          391         399         0.4732254
8  420        805          382         401         0.4720497
9  404        810          378         405         0.5370370
10 386        805          386         402         0.3937888
11 394        805          380         402         0.4931677
12 382        811          385         406         0.4722565
13 399        812          373         405         0.5788177
14 402        804          386         404         0.4452736
15 407        812          393         408         0.3411330
16 424        812          377         408         0.5529557
17 387        812          385         407         0.5369458
18 378        811          370         406         0.5474723
19 369        803          386         399         0.4022416
20 418        810          375         404         0.5641975
21 401        811          394         401         0.4377312
22 398        811          376         406         0.6251541
23 422        804          377         401         0.6604478
24 396        809          385         406         0.3844252
25 406        809          378         404         0.4165637
26 410        812          386         404         0.5110837
27 421        812          377         406         0.5369458
28 385        810          388         407         0.4358025
29 399        810          372         406         0.6197531
30 403        811          376         408         0.5573366

In [174]:
NBA_2018_stand

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Toronto       58   24     32-9  26-15 0.707      36-16      12-4     38-44-0
2  Philadelphia  51   31     31-10 20-21 0.622      31-21      8-8      38-44-0
3  Boston        49   33     28-13 21-20 0.598      35-17      10-6     39-42-1
4  Brooklyn      42   40     23-18 19-22 0.512      29-23      8-8      45-37-0
5  New York      17   65     9-32  8-33  0.207      11-41      2-14     32-49-1
6  Milwaukee     60   22     33-8  27-14 0.732      40-12      14-2     47-31-4
7  Indiana       48   34     29-12 19-22 0.585      33-19      11-5     41-41-0
8  Detroit       41   41     26-15 15-26 0.500      27-25      8-8      41-38-3
9  Chicago       22   60     9-32  13-28 0.268      16-36      3-13     35-46-1
10 Cleveland     19   63     13-28 6-35  0.232      15-37      4-12     37-43-2
11 Orlando       42   40     25-16 17-24 0.512      30-22      10-6     45-36-1
12 Charlotte     39   43     25-16 14-27 0.476      29-23      10-6     40-41-1
13 Miami         39   43     19-22 20-21 0.476      23-29      7-9      43-38-1
14 Washington    32   50     22-19 10-31 0.390      19-33      7-9      38-44-0
15 Atlanta       29   53     17-24 12-29 0.354      16-36      6-10     42-40-0
16 Denver        54   28     34-7  20-21 0.659      34-18      12-4     42-40-0
17 Portland      53   29     32-9  21-20 0.646      29-23      6-10     45-36-1
18 Utah          50   32     29-12 21-20 0.610      30-22      8-8      44-36-2
19 Oklahoma City 49   33     27-14 22-19 0.598      28-24      9-7      42-40-0
20 Minnesota     36   46     25-16 11-30 0.439      22-30      5-11     40-42-0
21 Golden State  57   25     30-11 27-14 0.695      35-17      13-3     35-46-1
22 L.A. Clippers 48   34     26-15 22-19 0.585      28-24      11-5     45-36-1
23 Sacramento    39   43     24-17 15-26 0.476      21-31      4-12     45-36-1
24 L.A. Lakers   37   45     22-19 15-26 0.451      25-27      9-7      35-45-2
25 Phoenix       19   63     12-29 7-34  0.232      11-41      3-13     36-46-0
26 Houston       53   29     31-10 22-19 0.646      32-20      10-6     40-39-3
27 San Antonio   48   34     32-9  16-25 0.585      30-22      10-6     43-37-2
28 Memphis       33   49     21-20 12-29 0.402      24-28      8-8      39-43-0
29 New Orleans   33   49     19-22 14-27 0.402      23-29      8-8      37-44-1
30 Dallas        33   49     24-17 9-32  0.402      18-34      4-12     45-34-3
   O_U     ⋯ Conf_Losses Div_Wins Div_Losses ATS_Wins ATS_Losses O_U_Wins
1  44-35-3 ⋯ 16          12        4         38       44         44
2  43-39-0 ⋯ 21           8        8         38       44         43
3  47-35-0 ⋯ 17          10        6         39       42         47
4  41-41-0 ⋯ 23           8        8         45       37         41
5  37-44-1 ⋯ 41           2       14         32       49         37
6  42-40-0 ⋯ 12          14        2         47       31         42
7  36-46-0 ⋯ 19          11        5         41       41         36
8  39-43-0 ⋯ 25           8        8         41       38         39
9  38-41-3 ⋯ 36           3       13         35       46         38
10 44-37-1 ⋯ 37           4       12         37       43         44
11 38-44-0 ⋯ 22          10        6         45       36         38
12 44-36-2 ⋯ 23          10        6         40       41         44
13 42-40-0 ⋯ 29           7        9         43       38         42
14 50-32-0 ⋯ 33           7        9         38       44         50
15 47-35-0 ⋯ 36           6       10         42       40         47
16 34-47-1 ⋯ 18          12        4         42       40         34
17 43-37-2 ⋯ 23           6       10         45       36         43
18 39-42-1 ⋯ 22           8        8         44       36         39
19 40-41-1 ⋯ 24           9        7         42       40         40
20 44-38-0 ⋯ 30           5       11         40       42         44
21 38-44-0 ⋯ 17          13        3         35       46         38
22 45-36-1 ⋯ 24          11        5         45       36         45
23 41-40-1 ⋯ 31           4       12         45       36         41
24 32-49-1 ⋯ 27           9        7         35       45         32
25 38-44-0 ⋯ 41           3       13         36       46         38
26 39-41-2 ⋯ 20          10        6         40       39         39
27 43-38-1 ⋯ 22          10        6         43       37         43
28 37-44-1 ⋯ 28           8        8         39       43         37
29 44-37-1 ⋯ 29           8        8         37       44         44
30 37-44-1 ⋯ 34           4       12         45       34         37
   O_U_Losses Games_Played Home_Played Away_Played
1  35         82           41          41
2  39         82           41          41
3  35         82           41          41
4  41         82           41          41
5  44         82           41          41
6  40         82           41          41
7  46         82           41          41
8  43         82           41          41
9  41         82           41          41
10 37         82           41          41
11 44         82           41          41
12 36         82           41          41
13 40         82           41          41
14 32         82           41          41
15 35         82           41          41
16 47         82           41          41
17 37         82           41          41
18 42         82           41          41
19 41         82           41          41
20 38         82           41          41
21 44         82           41          41
22 36         82           41          41
23 40         82           41          41
24 49         82           41          41
25 44         82           41          41
26 41         82           41          41
27 38         82           41          41
28 44         82           41          41
29 37         82           41          41
30 44         82           41          41