In [1]:
library(rvest)
library(polite)
library(tidyverse)
library(ggplot2)
library(scales)
library(dplyr)
library(forcats)
library(magrittr)
library(readr)
library(stringr)
library(lubridate)
library(purrr)
library(readxl)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.7
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()         masks stats::filter()
✖ readr::guess_encoding() masks rvest::guess_encoding()
✖ dplyr::lag()            masks stats::lag()


Attaching package: ‘scales’


The following object is masked from ‘package:purrr’:

    discard


The following object is masked from ‘package:readr’:

    col_factor



Attaching package: ‘magrittr’


The following object is masked from ‘package:purrr’:

    set_names


The following object is masked from ‘package:tidyr’:

    extract



Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

In [2]:
URL1 <- 'https://www.nfl.com/standings/league/2021/REG'
HTML_DOC1 <- rvest::read_html(x = URL1)
NFL_2021 <- HTML_DOC1 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL2 <- 'https://www.nfl.com/standings/league/2020/REG'
HTML_DOC2 <- rvest::read_html(x = URL2)
NFL_2020 <- HTML_DOC2 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL3 <- 'https://www.nfl.com/standings/league/2019/REG'
HTML_DOC3 <- rvest::read_html(x = URL3)
NFL_2019 <- HTML_DOC3 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL4 <- 'https://www.nfl.com/standings/league/2018/REG'
HTML_DOC4 <- rvest::read_html(x = URL4)
NFL_2018 <- HTML_DOC4 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL5 <- 'https://www.nfl.com/standings/league/2017/REG'
HTML_DOC5 <- rvest::read_html(x = URL5)
NFL_2017 <- HTML_DOC5 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL6 <- 'https://www.nfl.com/standings/league/2016/REG'
HTML_DOC6 <- rvest::read_html(x = URL6)
NFL_2016 <- HTML_DOC6 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL7 <- 'https://www.nfl.com/standings/league/2015/REG'
HTML_DOC7 <- rvest::read_html(x = URL7)
NFL_2015 <- HTML_DOC7 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL8 <- 'https://www.nfl.com/standings/league/2014/REG'
HTML_DOC8 <- rvest::read_html(x = URL8)
NFL_2014 <- HTML_DOC8 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL9 <- 'https://www.nfl.com/standings/league/2013/REG'
HTML_DOC9 <- rvest::read_html(x = URL9)
NFL_2013 <- HTML_DOC9 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL10 <- 'https://www.nfl.com/standings/league/2012/REG'
HTML_DOC10 <- rvest::read_html(x = URL10)
NFL_2012 <- HTML_DOC1 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL_curr <- 'https://www.nfl.com/standings/league/2022/REG'
HTML_DOC_curr <- rvest::read_html(x = URL_curr)
NFL_2022 <- HTML_DOC_curr %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

In [19]:
NFL_2022_stand <- as.data.frame(NFL_2022)
NFL_2022_stand <- NFL_2022_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '([A-Z][a-z]+ [A-Z][a-z]+ [A-Z][a-z]+) | ([A-Z][a-z]+ [A-Z][a-z]+) '),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2022_stand <- NFL_2022_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2021_stand <- as.data.frame(NFL_2021)
NFL_2021_stand <- NFL_2021_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2021_stand <- NFL_2021_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2020_stand <- as.data.frame(NFL_2020)
NFL_2020_stand <- NFL_2020_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2020_stand <- NFL_2020_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2019_stand <- as.data.frame(NFL_2019)
NFL_2019_stand <- NFL_2019_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2019_stand <- NFL_2019_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2018_stand <- as.data.frame(NFL_2018)
NFL_2018_stand <- NFL_2018_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2018_stand <- NFL_2018_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2017_stand <- as.data.frame(NFL_2017)
NFL_2017_stand <- NFL_2017_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2017_stand <- NFL_2017_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2016_stand <- as.data.frame(NFL_2016)
NFL_2016_stand <- NFL_2016_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2016_stand <- NFL_2016_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2015_stand <- as.data.frame(NFL_2015)
NFL_2015_stand <- NFL_2015_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2015_stand <- NFL_2015_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2014_stand <- as.data.frame(NFL_2014)
NFL_2014_stand <- NFL_2014_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2014_stand <- NFL_2014_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2013_stand <- as.data.frame(NFL_2013)
NFL_2013_stand <- NFL_2013_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2013_stand <- NFL_2013_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

NFL_2012_stand <- as.data.frame(NFL_2012)
NFL_2012_stand <- NFL_2012_stand %>% mutate(Team = str_extract(string = NFL.Team, pattern = '[A-Z][a-z]+ [A-Z][a-z]+'),Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer((str_extract(string = Home, pattern = '(?<= - )[0-9]+'))),
                   Road_Wins = as.integer(str_extract(string = Road, pattern = '[0-9]+')), Road_Losses = as.integer((str_extract(string = Road, pattern = '(?<= - )[0-9]+'))),
                   Div_Wins = as.integer(str_extract(string = Div, pattern = '[0-9]+')), Div_Losses = as.integer((str_extract(string = Div, pattern = '(?<= - )[0-9]+'))),
                   Conf_Wins = as.integer(str_extract(string = Conf, pattern = '[0-9]+')), Conf_Losses = as.integer((str_extract(string = Conf, pattern = '(?<= - )[0-9]+'))), Games_Played = W + T + L)
NFL_2012_stand <- NFL_2012_stand %>% select(Team, W, L, T, PCT, PF, PA, Home_Wins, Home_Losses, Road_Wins, Road_Losses, Div_Wins, Div_Losses, Conf_Wins, Conf_Losses, Games_Played)

In [20]:
NFL_stand <- NFL_2022_stand %>% inner_join(NFL_2021_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2020_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2019_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2018_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2017_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2016_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2015_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2014_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2013_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_stand <- NFL_stand %>% inner_join(NFL_2012_stand, by = "Team") %>% mutate(W = W.x + W.y, L = L.x + L.y, T = T.x + T.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Road_Wins = Road_Wins.x + Road_Wins.y, Road_Losses = Road_Losses.x + Road_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, Games_Played = Games_Played.x + Games_Played.y)
NFL_stand <- NFL_stand %>% mutate(PCT = (W + (T*.5))/Games_Played)
NFL_stand <- NFL_stand %>% select(Team,W,L,T,Home_Wins,Home_Losses,Road_Wins,Road_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,PCT,Games_Played)

NFL_2022_stand

   Team W  L T PCT   PF  PA  Home_Wins Home_Losses Road_Wins Road_Losses
1  NA    1 9 1 0.136 174 260 0         4           1         5
2  NA    3 9 0 0.250 251 305 2         3           1         6
3  NA    3 8 0 0.273 157 194 2         3           1         5
4  NA    3 8 0 0.273 178 253 2         4           1         4
5  NA    4 8 0 0.333 264 321 1         6           3         2
6  NA    4 8 0 0.333 230 266 4         3           0         5
7  NA    4 7 0 0.364 263 286 3         3           1         4
8  NA    4 7 0 0.364 275 310 2         4           2         3
9  NA    4 8 0 0.333 235 283 3         3           1         5
10 NA    4 7 1 0.375 190 244 2         4           2         3
11 NA    4 7 0 0.364 244 232 3         3           1         4
12 NA    4 7 0 0.364 265 276 2         2           2         5
13 NA    4 8 0 0.333 249 280 3         4           1         4
14 NA    4 7 0 0.364 194 261 2         3           2         4
15 NA    5 7 0 0.417 272 293 4         2           1         5
16 NA    5 6 0 0.455 200 203 3         3           2         3
17 NA    6 5 0 0.545 252 282 2         3           4         2
18 NA    6 6 0 0.500 249 226 3         3           3         3
19 NA    6 5 0 0.545 291 281 3         2           3         3
20 NA    7 4 0 0.636 275 227 3         2           4         2
21 NA    7 4 0 0.636 285 231 3         1           4         3
22 NA    7 4 0 0.636 225 232 4         2           3         2
23 NA    7 4 0 0.636 230 196 3         3           4         1
24 NA    7 4 0 0.636 249 173 4         1           3         3
25 NA    7 4 0 0.636 209 205 3         2           4         2
26 NA    7 5 0 0.583 233 236 3         3           4         2
27 NA    8 3 0 0.727 279 187 5         1           3         2
28 NA    8 3 0 0.727 282 256 5         1           3         2
29 NA    9 3 0 0.750 333 209 4         1           5         2
30 NA    9 2 0 0.818 326 243 5         1           4         1
31 NA    9 2 0 0.818 262 257 5         1           4         1
32 NA   10 1 0 0.909 303 216 5         1           5         0
   Div_Wins Div_Losses Conf_Wins Conf_Losses Games_Played
1  1        1          1         5           11
2  0        3          1         7           12
3  0        3          2         6           11
4  1        3          3         6           11
5  1        4          3         6           12
6  3        1          3         5           12
7  2        1          2         6           11
8  2        1          4         4           11
9  1        2          3         5           12
10 1        3          4         5           12
11 1        2          4         4           11
12 2        2          3         5           11
13 1        2          3         5           12
14 1        2          2         6           11
15 1        3          4         5           12
16 2        1          5         2           11
17 2        2          4         3           11
18 2        2          5         3           12
19 2        1          4         4           11
20 2        0          4         3           11
21 1        3          4         3           11
22 0        2          3         4           11
23 2        2          5         4           11
24 4        0          6         2           11
25 3        0          5         3           11
26 1        2          4         4           12
27 3        1          7         3           11
28 2        1          6         2           11
29 1        2          6         2           12
30 3        0          5         2           11
31 3        0          6         2           11
32 2        1          6         1           11

In [5]:
URL1_nba <- 'https://www.covers.com/sport/basketball/nba/standings'
HTML_DOC1_nba <- rvest::read_html(x = URL1_nba)
NBA_2022 <- HTML_DOC1_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL2_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2021-2022'
HTML_DOC2_nba <- rvest::read_html(x = URL2_nba)
NBA_2021 <- HTML_DOC2_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL3_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2020-2021'
HTML_DOC3_nba <- rvest::read_html(x = URL3_nba)
NBA_2020 <- HTML_DOC3_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL4_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2019-2020'
HTML_DOC4_nba <- rvest::read_html(x = URL4_nba)
NBA_2019 <- HTML_DOC4_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL5_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2018-2019'
HTML_DOC5_nba <- rvest::read_html(x = URL5_nba)
NBA_2018 <- HTML_DOC5_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL6_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2017-2018'
HTML_DOC6_nba <- rvest::read_html(x = URL6_nba)
NBA_2017 <- HTML_DOC6_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL7_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2016-2017'
HTML_DOC7_nba <- rvest::read_html(x = URL7_nba)
NBA_2016 <- HTML_DOC7_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL8_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2015-2016'
HTML_DOC8_nba <- rvest::read_html(x = URL8_nba)
NBA_2015 <- HTML_DOC8_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL9_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2014-2015'
HTML_DOC9_nba <- rvest::read_html(x = URL9_nba)
NBA_2014 <- HTML_DOC9_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL10_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2013-2014'
HTML_DOC10_nba <- rvest::read_html(x = URL10_nba)
NBA_2013 <- HTML_DOC10_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL11_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2012-2013'
HTML_DOC11_nba <- rvest::read_html(x = URL11_nba)
NBA_2012 <- HTML_DOC11_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

In [6]:
NBA_2022 <- as.data.frame(NBA_2022)
NBA_2022_standings <- NBA_2022 %>% filter(row(NBA_2022) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2022_stand <- NBA_2022_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2022_stand <- NBA_2022_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2022_stand <- NBA_2022_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2022_stand <- NBA_2022_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2022_stand <- NBA_2022_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2021 <- as.data.frame(NBA_2021)
NBA_2021_standings <- NBA_2021 %>% filter(row(NBA_2021) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2021_stand <- NBA_2021_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2021_stand <- NBA_2021_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2021_stand <- NBA_2021_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2021_stand <- NBA_2021_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2021_stand <- NBA_2021_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2020 <- as.data.frame(NBA_2020)
NBA_2020_standings <- NBA_2020 %>% filter(row(NBA_2020) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2020_stand <- NBA_2020_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2020_stand <- NBA_2020_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2020_stand <- NBA_2020_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2020_stand <- NBA_2020_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2020_stand <- NBA_2020_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2019 <- as.data.frame(NBA_2019)
NBA_2019_standings <- NBA_2019 %>% filter(row(NBA_2019) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2019_stand <- NBA_2019_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2019_stand <- NBA_2019_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2019_stand <- NBA_2019_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2019_stand <- NBA_2019_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2019_stand <- NBA_2019_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2018 <- as.data.frame(NBA_2018)
NBA_2018_standings <- NBA_2018 %>% filter(row(NBA_2018) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2018_stand <- NBA_2018_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2018_stand <- NBA_2018_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2018_stand <- NBA_2018_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2018_stand <- NBA_2018_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2018_stand <- NBA_2018_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2017 <- as.data.frame(NBA_2017)
NBA_2017_standings <- NBA_2017 %>% filter(row(NBA_2017) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2017_stand <- NBA_2017_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2017_stand <- NBA_2017_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2017_stand <- NBA_2017_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2017_stand <- NBA_2017_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2017_stand <- NBA_2017_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2016 <- as.data.frame(NBA_2016)
NBA_2016_standings <- NBA_2016 %>% filter(row(NBA_2016) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2016_stand <- NBA_2016_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2016_stand <- NBA_2016_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2016_stand <- NBA_2016_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2016_stand <- NBA_2016_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2016_stand <- NBA_2016_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2015 <- as.data.frame(NBA_2015)
NBA_2015_standings <- NBA_2015 %>% filter(row(NBA_2015) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2015_stand <- NBA_2015_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2015_stand <- NBA_2015_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2015_stand <- NBA_2015_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2015_stand <- NBA_2015_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2015_stand <- NBA_2015_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2014 <- as.data.frame(NBA_2014)
NBA_2014_standings <- NBA_2014 %>% filter(row(NBA_2014) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2014_stand <- NBA_2014_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2014_stand <- NBA_2014_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2014_stand <- NBA_2014_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2014_stand <- NBA_2014_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2014_stand <- NBA_2014_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2013 <- as.data.frame(NBA_2013)
NBA_2013_standings <- NBA_2013 %>% filter(row(NBA_2013) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2013_stand <- NBA_2013_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2013_stand <- NBA_2013_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2013_stand <- NBA_2013_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2013_stand <- NBA_2013_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2013_stand <- NBA_2013_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2012 <- as.data.frame(NBA_2012)
NBA_2012_standings <- NBA_2012 %>% filter(row(NBA_2012) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2012_stand <- NBA_2012_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2012_stand <- NBA_2012_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2012_stand <- NBA_2012_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9+]')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2012_stand <- NBA_2012_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2012_stand <- NBA_2012_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

In [7]:
NBA_stand <- NBA_2022_stand %>% inner_join(NBA_2021_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2020_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2019_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2018_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2017_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2016_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2015_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2014_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2013_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand <- NBA_stand %>% inner_join(NBA_2012_stand, by = "Team") %>% mutate(Wins = Wins.x + Wins.y, Losses = Losses.x + Losses.y, Home_Wins = Home_Wins.x + Home_Wins.y, Home_Losses = Home_Losses.x + Home_Losses.y,
                                                                                  Away_Wins = Away_Wins.x + Away_Wins.y, Away_Losses = Away_Losses.x + Away_Losses.y, Conf_Wins = Conf_Wins.x + Conf_Wins.y,Conf_Losses = Conf_Losses.x + Conf_Losses.y,
                                                                                  Div_Wins = Div_Wins.x + Div_Wins.y, Div_Losses = Div_Losses.x + Div_Losses.y, ATS_Wins = ATS_Wins.x + ATS_Wins.y, ATS_Losses = ATS_Losses.x + ATS_Losses.y, O_U_Wins = O_U_Wins.x + O_U_Wins.y, O_U_Losses = O_U_Losses.x + O_U_Losses.y,
                                                                                  Games_Played = Games_Played.x + Games_Played.y, Home_Played = Home_Played.x + Home_Played.y, Away_Played = Away_Played.x + Away_Played.y)
NBA_stand <- NBA_stand %>% mutate(Percentage = Wins/Games_Played)
NBA_stand <- NBA_stand %>% select(Team,Wins,Losses,Home_Wins,Home_Losses,Away_Wins,Away_Losses,Conf_Wins,Conf_Losses,Div_Wins,Div_Losses,ATS_Wins,ATS_Losses,O_U_Wins,O_U_Losses,Games_Played,Home_Played,Away_Played,Percentage)

NBA_stand

   Team          Wins Losses Home_Wins Home_Losses Away_Wins Away_Losses
1  Boston        464  357    238       148         201       209
2  Philadelphia  367  456    200       190         146       266
3  Toronto       494  327    255       136         220       191
4  Brooklyn      381  442    189       198         168       244
5  New York      326  490    154       225         144       265
6  Milwaukee     441  380    233       160         189       220
7  Cleveland     386  429    215       182         158       247
8  Indiana       442  379    233       151         182       228
9  Chicago       383  431    194       192         167       239
10 Detroit       320  498    178       213         125       285
11 Atlanta       402  415    217       169         162       246
12 Washington    389  433    214       178         155       255
13 Miami         476  347    238       140         204       207
14 Charlotte     361  453    196       194         151       259
15 Orlando       280  543    159       241         110       302
16 Denver        451  371    229       145         187       226
17 Utah          453  371    240       142         186       229
18 Minnesota     329  485    177       213         134       272
19 Portland      440  384    240       149         180       235
20 Oklahoma City 462  360    231       150         200       210
21 Phoenix       363  459    188       212         159       247
22 L.A. Clippers 514  309    258       125         227       184
23 Sacramento    319  501    165       227         136       274
24 Golden State  538  277    275       107         237       170
25 L.A. Lakers   343  476    172       212         144       264
26 New Orleans   361  460    196       200         150       260
27 Memphis       441  381    223       158         189       223
28 Dallas        419  405    217       175         180       230
29 San Antonio   503  318    256       121         215       197
30 Houston       455  366    230       151         198       215
   Conf_Wins Conf_Losses Div_Wins Div_Losses ATS_Wins ATS_Losses O_U_Wins
1  306       210          91       66        428      375        415
2  236       286          69       92        405      403        402
3  325       193         103       55        426      386        429
4  245       272          75       85        407      403        402
5  213       300          58       98        401      405        390
6  290       225          92       67        396      412        420
7  261       257          73       86        368      428        400
8  286       231          88       69        412      396        402
9  265       250          80       79        389      419        379
10 215       301          64       96        396      408        411
11 252       266          82       75        402      403        412
12 252       267          76       83        397      409        425
13 307       208         104       56        415      387        415
14 245       267          79       77        392      401        395
15 175       340          54      104        383      424        397
16 277       242          84       76        405      403        427
17 278       243          83       73        405      397        387
18 201       309          60       95        371      427        431
19 259       260          80       75        405      404        422
20 282       234          85       73        425      383        394
21 220       299          63       97        411      398        409
22 317       208         106       53        427      387        405
23 187       327          62       97        394      406        412
24 333       183         111       49        402      397        381
25 205       315          56      102        372      431        398
26 218       301          64       94        400      409        423
27 275       242          75       83        418      392        385
28 250       266          76       81        425      386        400
29 304       213          95       60        416      391        405
30 278       242          82       74        395      418        405
   O_U_Losses Games_Played Home_Played Away_Played Percentage
1  395        821          386         410         0.5651644
2  408        823          390         412         0.4459295
3  386        821          391         411         0.6017052
4  409        823          387         412         0.4629405
5  417        816          379         409         0.3995098
6  394        821          393         409         0.5371498
7  406        815          397         405         0.4736196
8  410        821          384         410         0.5383678
9  425        814          386         406         0.4705160
10 390        818          391         410         0.3911980
11 400        817          386         408         0.4920441
12 386        822          392         410         0.4732360
13 403        823          378         411         0.5783718
14 407        814          390         410         0.4434889
15 414        823          400         412         0.3402187
16 384        822          374         413         0.5486618
17 428        824          382         415         0.5497573
18 374        814          390         406         0.4041769
19 392        824          389         415         0.5339806
20 420        822          381         410         0.5620438
21 406        822          400         406         0.4416058
22 405        823          383         411         0.6245443
23 399        820          392         410         0.3890244
24 426        815          382         407         0.6601227
25 411        819          384         408         0.4188034
26 392        821          396         410         0.4397077
27 426        822          381         412         0.5364964
28 415        824          392         410         0.5084951
29 404        821          377         412         0.6126675
30 408        821          381         413         0.5542022

In [9]:
#NBA HOME WINS
NBA_stand %>% summarize(Total_Home_Wins = sum(Home_Wins), Total_Games = sum(Home_Wins, Home_Losses), PCT = Total_Home_Wins/Total_Games)

  Total_Home_Wins Total_Games PCT
1 6308            11460       0.5504363

In [10]:
#NBA ROAD WINS
NBA_stand %>% summarize(Total_Away_Wins = sum(Away_Wins), Total_Games = sum(Away_Wins, Away_Losses), PCT = Total_Away_Wins/Total_Games)

  Total_Away_Wins Total_Games PCT
1 5152            12149       0.4240678

In [11]:
#NFL HOME WINS
NFL_stand %>% summarize(Total_Home_Wins = sum(Home_Wins), Total_Games = sum(Home_Wins, Home_Losses), PCT = Total_Home_Wins/Total_Games)

  Total_Home_Wins Total_Games PCT
1 168242          352583      0.4771699

In [13]:
#NFL ROAD WINS
NFL_stand %>% summarize(Total_Away_Wins = sum(Road_Wins), Total_Games = sum(Road_Wins, Road_Losses), PCT = Total_Away_Wins/Total_Games)

  Total_Away_Wins Total_Games PCT
1 139329          349514      0.3986364

In [2]:
#NBA Home WINS BAR Graph
NBA_stand %>% ggplot(aes(x = Home_wins, y = Away_Wins, color = Team)) %>% geom_point()

ERROR: Error in NBA_stand %>% ggplot(aes(x = Home_wins, y = Away_Wins, color = Team)) %>% : could not find function "%>%"

In [23]:
NBA_stand %>% arrange(-ATS_Wins) %>% head(3)

  Team          Wins Losses Home_Wins Home_Losses Away_Wins Away_Losses
1 Dallas        415  398    213       173         180       225
2 Toronto       490  322    252       135         219       187
3 L.A. Clippers 508  304    254       123         225       181
  Conf_Wins Conf_Losses Div_Wins Div_Losses ATS_Wins ATS_Losses O_U_Wins
1 246       264          76      80         423      377        393
2 322       190         103      54         422      381        424
3 313       204         106      52         421      382        400
  O_U_Losses Games_Played Home_Played Away_Played Percentage
1 411        813          386         405         0.5104551
2 382        812          387         406         0.6034483
3 399        812          377         406         0.6256158

In [ ]:
NBA_stand %>% ggplot(aes(x = Team, y = Home_Wins, )) +  geom_bar(stat = 'identity', position = position_dodge())+coord_flip()