In [1]:
library(rvest)
library(polite)
library(tidyverse)
library(ggplot2)
library(scales)
library(dplyr)
library(forcats)
library(magrittr)
library(readr)
library(stringr)
library(lubridate)
library(purrr)
library(readxl)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.7
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()         masks stats::filter()
✖ readr::guess_encoding() masks rvest::guess_encoding()
✖ dplyr::lag()            masks stats::lag()


Attaching package: ‘scales’


The following object is masked from ‘package:purrr’:

    discard


The following object is masked from ‘package:readr’:

    col_factor



Attaching package: ‘magrittr’


The following object is masked from ‘package:purrr’:

    set_names


The following object is masked from ‘package:tidyr’:

    extract



Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

In [2]:
URL1 <- 'https://www.nfl.com/standings/league/2021/REG'
HTML_DOC1 <- rvest::read_html(x = URL1)
NFL_2021 <- HTML_DOC1 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL2 <- 'https://www.nfl.com/standings/league/2020/REG'
HTML_DOC2 <- rvest::read_html(x = URL2)
NFL_2020 <- HTML_DOC2 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL3 <- 'https://www.nfl.com/standings/league/2019/REG'
HTML_DOC3 <- rvest::read_html(x = URL3)
NFL_2019 <- HTML_DOC3 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL4 <- 'https://www.nfl.com/standings/league/2018/REG'
HTML_DOC4 <- rvest::read_html(x = URL4)
NFL_2018 <- HTML_DOC4 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL5 <- 'https://www.nfl.com/standings/league/2017/REG'
HTML_DOC5 <- rvest::read_html(x = URL5)
NFL_2017 <- HTML_DOC5 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL6 <- 'https://www.nfl.com/standings/league/2016/REG'
HTML_DOC6 <- rvest::read_html(x = URL6)
NFL_2016 <- HTML_DOC6 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL7 <- 'https://www.nfl.com/standings/league/2015/REG'
HTML_DOC7 <- rvest::read_html(x = URL7)
NFL_2015 <- HTML_DOC7 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL8 <- 'https://www.nfl.com/standings/league/2014/REG'
HTML_DOC8 <- rvest::read_html(x = URL8)
NFL_2014 <- HTML_DOC8 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL9 <- 'https://www.nfl.com/standings/league/2013/REG'
HTML_DOC9 <- rvest::read_html(x = URL9)
NFL_2013 <- HTML_DOC9 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL10 <- 'https://www.nfl.com/standings/league/2012/REG'
HTML_DOC10 <- rvest::read_html(x = URL10)
NFL_2012 <- HTML_DOC1 %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

URL_curr <- 'https://www.nfl.com/standings/league/2022/REG'
HTML_DOC_curr <- rvest::read_html(x = URL_curr)
NFL_2022 <- HTML_DOC_curr %>% rvest::html_elements('.d3-o-table--horizontal-scroll .d3-o-table') %>% rvest::html_table()

In [35]:
NFL_2021 <- NFL_2021 %>% str_extract(string = NFL Team, pattern = '/w [A-Z][a-z]+')

ERROR: Error in parse(text = x, srcfile = src): <text>:1:51: unexpected symbol
1: NFL_2021 <- NFL_2021 %>% str_extract(string = NFL Team
                                                      ^

In [3]:
NFL_2021

[[1]]
# A tibble: 32 × 17
   `NFL Team`        W     L     T   PCT    PF    PA `Net Pts` Home  Road  Div
   <chr>         <int> <int> <int> <dbl> <int> <int>     <int> <chr> <chr> <chr>
 1 Detroit Lion…     3    13     1 0.206   325   467      -142 3 - … 0 - … 2 - …
 2 Jacksonville…     3    14     0 0.176   253   457      -204 3 - … 0 - … 1 - …
 3 Houston Texa…     4    13     0 0.235   280   452      -172 2 - … 2 - … 3 - …
 4 New York Gia…     4    13     0 0.235   258   416      -158 3 - … 1 - … 1 - …
 5 New York Jet…     4    13     0 0.235   310   504      -194 3 - … 1 - … 0 - …
 6 Carolina Pan…     5    12     0 0.294   304   404      -100 2 - … 3 - … 2 - …
 7 Chicago Bear…     6    11     0 0.353   311   407       -96 3 - … 3 - … 2 - …
 8 Atlanta Falc…     7    10     0 0.412   313   459      -146 2 - … 5 - … 2 - …
 9 Denver Bronc…     7    10     0 0.412   335   322        13 4 - … 3 - … 1 - …
10 Seattle Seah…     7    10     0 0.412   395   366        29 3 - … 4 - … 3 - …
# … with 22 more rows, and 6 more variables: Pct <dbl>, Conf <chr>, Pct <dbl>,
#   `Non-Conf` <chr>, Strk <chr>, `Last 5` <chr>

In [69]:
URL1_nba <- 'https://www.covers.com/sport/basketball/nba/standings'
HTML_DOC1_nba <- rvest::read_html(x = URL1_nba)
NBA_2022 <- HTML_DOC1_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL2_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2021-2022'
HTML_DOC2_nba <- rvest::read_html(x = URL2_nba)
NBA_2021 <- HTML_DOC2_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL3_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2020-2021'
HTML_DOC3_nba <- rvest::read_html(x = URL3_nba)
NBA_2020 <- HTML_DOC3_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL4_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2019-2020'
HTML_DOC4_nba <- rvest::read_html(x = URL4_nba)
NBA_2019 <- HTML_DOC4_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL5_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2018-2019'
HTML_DOC5_nba <- rvest::read_html(x = URL5_nba)
NBA_2018 <- HTML_DOC5_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL6_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2017-2018'
HTML_DOC6_nba <- rvest::read_html(x = URL6_nba)
NBA_2017 <- HTML_DOC6_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL7_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2016-2017'
HTML_DOC7_nba <- rvest::read_html(x = URL7_nba)
NBA_2016 <- HTML_DOC7_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL8_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2015-2016'
HTML_DOC8_nba <- rvest::read_html(x = URL8_nba)
NBA_2015 <- HTML_DOC8_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL9_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2014-2015'
HTML_DOC9_nba <- rvest::read_html(x = URL9_nba)
NBA_2014 <- HTML_DOC9_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL10_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2013-2014'
HTML_DOC10_nba <- rvest::read_html(x = URL10_nba)
NBA_2013 <- HTML_DOC10_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

URL11_nba <- 'https://www.covers.com/sport/basketball/nba/standings/2012-2013'
HTML_DOC11_nba <- rvest::read_html(x = URL11_nba)
NBA_2012 <- HTML_DOC11_nba %>% rvest::html_elements('.tab-content') %>% rvest::html_table()

In [64]:
NBA_2022 <- as.data.frame(NBA_2022)
NBA_2022_standings <- NBA_2022 %>% filter(row(NBA_2022) > 74) 
NBA_2022_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4,
                             Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)

   Team
1  L.A. Lakers\r\n                                    \r\n                                    \r\n                                        LAL
2  L.A. Clippers\r\n                                    \r\n                                    \r\n                                        LAC
3  Golden State\r\n                                    \r\n                                    \r\n                                        GS
4  Sacramento\r\n                                    \r\n                                    \r\n                                        SAC
5  Phoenix\r\n                                    \r\n                                    \r\n                                        PHO
6  Memphis\r\n                                    \r\n                                    \r\n                                        MEM
7  Utah\r\n                                    \r\n                                    \r\n                                        UTA
8  Minnesota\r\n                                    \r\n                                    \r\n                                        MIN
9  Milwaukee\r\n                                    \r\n                                    \r\n                                        MIL
10 Houston\r\n                                    \r\n                                    \r\n                                        HOU
11 Portland\r\n                                    \r\n                                    \r\n                                        POR
12 Oklahoma City\r\n                                    \r\n                                    \r\n                                        OKC
13 Atlanta\r\n                                    \r\n                                    \r\n                                        ATL
14 Detroit\r\n                                    \r\n                                    \r\n                                        DET
15 San Antonio\r\n                                    \r\n                                    \r\n                                        SA
16 New Orleans\r\n                                    \r\n                                    \r\n                                        NO
17 Miami\r\n                                    \r\n                                    \r\n                                        MIA
18 Indiana\r\n                                    \r\n                                    \r\n                                        IND
19 Dallas\r\n                                    \r\n                                    \r\n                                        DAL
20 Washington\r\n                                    \r\n                                    \r\n                                        WAS
21 Denver\r\n                                    \r\n                                    \r\n                                        DEN
22 Charlotte\r\n                                    \r\n                                    \r\n                                        CHA
23 Orlando\r\n                                    \r\n                                    \r\n                                        ORL
24 Chicago\r\n                                    \r\n                                    \r\n                                        CHI
25 Cleveland\r\n                                    \r\n                                    \r\n                                        CLE
26 New York\r\n                                    \r\n                                    \r\n                                        NY
27 Boston\r\n                                    \r\n                                    \r\n                                        BOS
28 Toronto\r\n                                    \r\n                                    \r\n                                        TOR
29 Philadelphia\r\n                                    \r\n                                    \r\n                                        PHI
30 Brooklyn\r\n                                    \r\n                                    \r\n                                        BK
   Wins Losses Percentage Home Away Var.7 Var.8 Var.9 Var.10 Var.11 Var.12
1  2    8      .200       2-7  0-2  2-4   0-4   2-8-0 5-5-0  NA     NA
2  6    5      .545       5-5  2-1  2-3   4-2   4-7-0 2-9-0  NA     NA
3  4    7      .364       3-3  3-1  4-1   0-6   3-8-0 7-3-1  NA     NA
4  3    6      .333       0-5  0-3  1-3   2-3   6-3-0 3-6-0  NA     NA
5  7    3      .700       7-2  2-0  6-1   1-2   6-4-0 3-7-0  NA     NA
6  7    4      .636       3-3  1-1  4-1   3-3   4-7-0 6-5-0  NA     NA
7  9    3      .750       9-3  2-1  5-0   4-3   9-3-0 5-7-0  NA     NA
8  5    6      .455       5-4  2-1  4-4   1-2   4-7-0 3-8-0  NA     NA
9  9    1      .900       6-1  2-0  7-0   2-1   8-2-0 3-7-0  NA     NA
10 2    9      .182       1-7  0-1  1-2   1-7   6-5-0 6-5-0  NA     NA
11 7    3      .700       6-2  1-0  3-2   4-1   8-2-0 3-7-0  NA     NA
12 4    6      .400       3-4  0-4  3-2   1-4   6-4-0 5-5-0  NA     NA
13 7    3      .700       5-3  1-1  4-1   3-2   5-5-0 6-4-0  NA     NA
14 3    8      .273       1-8  0-4  3-3   0-5   5-6-0 6-5-0  NA     NA
15 5    6      .455       2-4  0-0  2-4   3-2   6-5-0 5-6-0  NA     NA
16 5    5      .500       3-3  1-0  2-1   3-4   4-6-0 8-2-0  NA     NA
17 4    7      .364       1-4  0-0  3-4   1-3   2-9-0 5-6-0  NA     NA
18 5    5      .500       4-4  1-1  3-2   2-3   6-4-0 5-5-0  NA     NA
19 6    3      .667       2-3  1-1  5-1   1-2   3-5-1 6-3-0  NA     NA
20 5    6      .455       5-5  1-0  2-3   3-3   5-5-1 4-7-0  NA     NA
21 7    3      .700       7-3  3-2  4-0   3-3   5-5-0 5-5-0  NA     NA
22 3    8      .273       1-5  1-2  1-4   2-4   4-6-1 5-5-1  NA     NA
23 2    9      .182       1-5  1-1  2-3   0-6   4-6-1 7-4-0  NA     NA
24 6    6      .500       6-5  1-1  4-2   2-4   7-4-1 5-7-0  NA     NA
25 8    2      .800       7-1  2-0  4-0   4-2   8-2-0 6-4-0  NA     NA
26 5    5      .500       4-4  1-1  3-2   2-3   5-5-0 6-4-0  NA     NA
27 7    3      .700       6-3  2-0  3-1   4-2   4-6-0 6-4-0  NA     NA
28 6    5      .545       5-4  1-2  4-1   2-4   8-3-0 5-6-0  NA     NA
29 5    6      .455       4-5  1-3  2-4   3-2   5-6-0 5-6-0  NA     NA
30 4    7      .364       4-3  1-0  2-4   2-3   3-7-1 4-7-0  NA     NA
   Var.13 Var.14
1  NA     NA
2  NA     NA
3  NA     NA
4  NA     NA
5  NA     NA
6  NA     NA
7  NA     NA
8  NA     NA
9  NA     NA
10 NA     NA
11 NA     NA
12 NA     NA
13 NA     NA
14 NA     NA
15 NA     NA
16 NA     NA
17 NA     NA
18 NA     NA
19 NA     NA
20 NA     NA
21 NA     NA
22 NA     NA
23 NA     NA
24 NA     NA
25 NA     NA
26 NA     NA
27 NA     NA
28 NA     NA
29 NA     NA
30 NA     NA

Rows: 30
Columns: 14
$ Eastern.Conference <chr> "L.A. Lakers\r\n                                   …
$ Var.2              <chr> "2", "6", "4", "3", "7", "7", "9", "5", "9", "2", "…
$ Var.3              <chr> "8", "5", "7", "6", "3", "4", "3", "6", "1", "9", "…
$ Var.4              <chr> ".200", ".545", ".364", ".333", ".700", ".636", ".7…
$ Var.5              <chr> "2-7", "5-5", "3-3", "0-5", "7-2", "3-3", "9-3", "5…
$ Var.6              <chr> "0-2", "2-1", "3-1", "0-3", "2-0", "1-1", "2-1", "2…
$ Var.7              <chr> "2-4", "2-3", "4-1", "1-3", "6-1", "4-1", "5-0", "4…
$ Var.8              <chr> "0-4", "4-2", "0-6", "2-3", "1-2", "3-3", "4-3", "1…
$ Var.9              <chr> "2-8-0", "4-7-0", "3-8-0", "6-3-0", "6-4-0", "4-7-0…
$ Var.10             <chr> "5-5-0", "2-9-0", "7-3-1", "3-6-0", "3-7-0", "6-5-0…
$ Var.11             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ Var.12             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ Var.13             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ Var.14             <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…

In [143]:
NBA_2022 <- as.data.frame(NBA_2022)
NBA_2022_standings <- NBA_2022 %>% filter(row(NBA_2022) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2022_stand <- NBA_2022_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2022_stand <- NBA_2022_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2022_stand <- NBA_2022_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2022_stand <- NBA_2022_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2022_stand <- NBA_2022_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2021 <- as.data.frame(NBA_2021)
NBA_2021_standings <- NBA_2021 %>% filter(row(NBA_2021) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2021_stand <- NBA_2021_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2021_stand <- NBA_2021_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2021_stand <- NBA_2021_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2021_stand <- NBA_2021_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2021_stand <- NBA_2021_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2020 <- as.data.frame(NBA_2020)
NBA_2020_standings <- NBA_2020 %>% filter(row(NBA_2020) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2020_stand <- NBA_2020_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2020_stand <- NBA_2020_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2020_stand <- NBA_2020_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2020_stand <- NBA_2020_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2020_stand <- NBA_2020_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2019 <- as.data.frame(NBA_2019)
NBA_2019_standings <- NBA_2019 %>% filter(row(NBA_2019) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2019_stand <- NBA_2019_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2019_stand <- NBA_2019_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2019_stand <- NBA_2019_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2019_stand <- NBA_2019_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2019_stand <- NBA_2019_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2018 <- as.data.frame(NBA_2018)
NBA_2018_standings <- NBA_2018 %>% filter(row(NBA_2018) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2018_stand <- NBA_2018_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2018_stand <- NBA_2018_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2018_stand <- NBA_2018_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2018_stand <- NBA_2018_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2018_stand <- NBA_2018_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2017 <- as.data.frame(NBA_2017)
NBA_2017_standings <- NBA_2017 %>% filter(row(NBA_2017) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2017_stand <- NBA_2017_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2017_stand <- NBA_2017_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2017_stand <- NBA_2017_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2017_stand <- NBA_2017_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2017_stand <- NBA_2017_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2016 <- as.data.frame(NBA_2016)
NBA_2016_standings <- NBA_2016 %>% filter(row(NBA_2016) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2016_stand <- NBA_2016_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2016_stand <- NBA_2016_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2016_stand <- NBA_2016_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2016_stand <- NBA_2016_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2016_stand <- NBA_2016_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2015 <- as.data.frame(NBA_2015)
NBA_2015_standings <- NBA_2015 %>% filter(row(NBA_2015) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2015_stand <- NBA_2015_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2015_stand <- NBA_2015_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2015_stand <- NBA_2015_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2015_stand <- NBA_2015_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2015_stand <- NBA_2015_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2014 <- as.data.frame(NBA_2014)
NBA_2014_standings <- NBA_2014 %>% filter(row(NBA_2014) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2014_stand <- NBA_2014_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2014_stand <- NBA_2014_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2014_stand <- NBA_2014_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-99]')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-99]')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-99]')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-99]')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-99]')))
NBA_2014_stand <- NBA_2014_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2014_stand <- NBA_2014_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2013 <- as.data.frame(NBA_2013)
NBA_2013_standings <- NBA_2013 %>% filter(row(NBA_2013) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2013_stand <- NBA_2013_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2013_stand <- NBA_2013_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2013_stand <- NBA_2013_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9]+')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')),O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2013_stand <- NBA_2013_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2013_stand <- NBA_2013_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

NBA_2012 <- as.data.frame(NBA_2012)
NBA_2012_standings <- NBA_2012 %>% filter(row(NBA_2012) < 38) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'NBA')) %>% filter(!str_detect(string = Eastern.Conference, pattern = 'Conference'))
NBA_2012_stand <- NBA_2012_standings %>% rename(Team = Eastern.Conference, Wins = Var.2, Losses = Var.3, Percentage = Var.4, Home = Var.5, Away = Var.6, Conference = Var.7, Division = Var.8, ATS = Var.9, O_U = Var.10)
NBA_2012_stand <- NBA_2012_stand %>% select(Team, Wins, Losses, Home, Away, Percentage, Conference, Division, ATS, O_U)   
NBA_2012_stand <- NBA_2012_stand %>% mutate(Home_Wins = as.integer(str_extract(string = Home, pattern = '[0-9+]')), Home_Losses = as.integer(str_extract(string = Home, pattern = '(?<=-)[0-9]+')),Away_Wins = as.integer(str_extract(string = Away, pattern = '[0-9]+')), Away_Losses = as.integer(str_extract(string = Away, pattern = '(?<=-)[0-9]+')),
                         Conf_Wins = as.integer(str_extract(string = Conference, pattern = '[0-9]+')), Conf_Losses = as.integer(str_extract(string = Conference, pattern = '(?<=-)[0-9]+')), Div_Wins = as.integer(str_extract(string = Division, pattern = '[0-9]+')), Div_Losses = as.integer(str_extract(string = Division, pattern = '(?<=-)[0-9]+')),
                         ATS_Wins = as.integer(str_extract(string = ATS, pattern = '[0-9]+')), ATS_Losses = as.integer(str_extract(string = ATS, pattern = '(?<=-)[0-9]+')), O_U_Wins = as.integer(str_extract(string = O_U, pattern = '[0-9]+')), O_U_Losses = as.integer(str_extract(string = O_U, pattern = '(?<=-)[0-9]+')))
NBA_2012_stand <- NBA_2012_stand %>% mutate(Wins = as.integer(Wins), Losses = as.integer(Losses), Percentage = as.double(Percentage))
NBA_2012_stand <- NBA_2012_stand %>% mutate(Games_Played = Wins + Losses, Home_Played = Home_Wins + Home_Losses, Away_Played = Away_Wins + Away_Losses)

In [144]:
NBA_2022_stand
NBA_2021_stand
NBA_2020_stand
NBA_2019_stand
NBA_2018_stand
NBA_2017_stand
NBA_2016_stand
NBA_2015_stand
NBA_2014_stand
NBA_2013_stand
NBA_2012_stand

   Team          Wins Losses Home Away Percentage Conference Division ATS
1  Boston        7    3      3-1  4-2  0.700      6-3        2-0      4-6-0
2  Toronto       6    5      4-1  2-4  0.545      5-4        1-2      8-3-0
3  New York      5    5      3-2  2-3  0.500      4-4        1-1      5-5-0
4  Philadelphia  5    6      2-4  3-2  0.455      4-5        1-3      5-6-0
5  Brooklyn      4    7      2-4  2-3  0.364      4-3        1-0      3-7-1
6  Milwaukee     9    1      7-0  2-1  0.900      6-1        2-0      8-2-0
7  Cleveland     8    2      4-0  4-2  0.800      7-1        2-0      8-2-0
8  Chicago       6    6      4-2  2-4  0.500      6-5        1-1      7-4-1
9  Indiana       5    5      3-2  2-3  0.500      4-4        1-1      6-4-0
10 Detroit       3    8      3-3  0-5  0.273      1-8        0-4      5-6-0
11 Atlanta       7    3      4-1  3-2  0.700      5-3        1-1      5-5-0
12 Washington    5    6      2-3  3-3  0.455      5-5        1-0      5-5-1
13 Miami         4    7      3-4  1-3  0.364      1-4        0-0      2-9-0
14 Charlotte     3    8      1-4  2-4  0.273      1-5        1-2      4-6-1
15 Orlando       2    9      2-3  0-6  0.182      1-5        1-1      4-6-1
16 Utah          9    3      5-0  4-3  0.750      9-3        2-1      9-3-0
17 Portland      7    3      3-2  4-1  0.700      6-2        1-0      8-2-0
18 Denver        7    3      4-0  3-3  0.700      7-3        3-2      5-5-0
19 Minnesota     5    6      4-4  1-2  0.455      5-4        2-1      4-7-0
20 Oklahoma City 4    6      3-2  1-4  0.400      3-4        0-4      6-4-0
21 Phoenix       7    3      6-1  1-2  0.700      7-2        2-0      6-4-0
22 L.A. Clippers 6    5      2-3  4-2  0.545      5-5        2-1      4-7-0
23 Golden State  4    7      4-1  0-6  0.364      3-3        3-1      3-8-0
24 Sacramento    3    6      1-3  2-3  0.333      0-5        0-3      6-3-0
25 L.A. Lakers   2    8      2-4  0-4  0.200      2-7        0-2      2-8-0
26 Dallas        6    3      5-1  1-2  0.667      2-3        1-1      3-5-1
27 Memphis       7    4      4-1  3-3  0.636      3-3        1-1      4-7-0
28 New Orleans   5    5      2-1  3-4  0.500      3-3        1-0      4-6-0
29 San Antonio   5    6      2-4  3-2  0.455      2-4        0-0      6-5-0
30 Houston       2    9      1-2  1-7  0.182      1-7        0-1      6-5-0
   O_U   ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  6-4-0 ⋯ 0          4        6          0       6        4          0
2  5-6-0 ⋯ 2          8        3          0       5        6          0
3  6-4-0 ⋯ 1          5        5          0       6        4          0
4  5-6-0 ⋯ 3          5        6          0       5        6          0
5  4-7-0 ⋯ 0          3        7          1       4        7          0
6  3-7-0 ⋯ 0          8        2          0       3        7          0
7  6-4-0 ⋯ 0          8        2          0       6        4          0
8  5-7-0 ⋯ 1          7        4          1       5        7          0
9  5-5-0 ⋯ 1          6        4          0       5        5          0
10 6-5-0 ⋯ 4          5        6          0       6        5          0
11 6-4-0 ⋯ 1          5        5          0       6        4          0
12 4-7-0 ⋯ 0          5        5          1       4        7          0
13 5-6-0 ⋯ 0          2        9          0       5        6          0
14 5-5-1 ⋯ 2          4        6          1       5        5          1
15 7-4-0 ⋯ 1          4        6          1       7        4          0
16 5-7-0 ⋯ 1          9        3          0       5        7          0
17 3-7-0 ⋯ 0          8        2          0       3        7          0
18 5-5-0 ⋯ 2          5        5          0       5        5          0
19 3-8-0 ⋯ 1          4        7          0       3        8          0
20 5-5-0 ⋯ 4          6        4          0       5        5          0
21 3-7-0 ⋯ 0          6        4          0       3        7          0
22 2-9-0 ⋯ 1          4        7          0       2        9          0
23 7-3-1 ⋯ 1          3        8          0       7        3          1
24 3-6-0 ⋯ 3          6        3          0       3        6          0
25 5-5-0 ⋯ 2          2        8          0       5        5          0
26 6-3-0 ⋯ 1          3        5          1       6        3          0
27 6-5-0 ⋯ 1          4        7          0       6        5          0
28 8-2-0 ⋯ 0          4        6          0       8        2          0
29 5-6-0 ⋯ 0          6        5          0       5        6          0
30 6-5-0 ⋯ 1          6        5          0       6        5          0
   Games_Played Home_Played Away_Played
1  10           4           6
2  11           5           6
3  10           5           5
4  11           6           5
5  11           6           5
6  10           7           3
7  10           4           6
8  12           6           6
9  10           5           5
10 11           6           5
11 10           5           5
12 11           5           6
13 11           7           4
14 11           5           6
15 11           5           6
16 12           5           7
17 10           5           5
18 10           4           6
19 11           8           3
20 10           5           5
21 10           7           3
22 11           5           6
23 11           5           6
24  9           4           5
25 10           6           4
26  9           6           3
27 11           5           6
28 10           3           7
29 11           6           5
30 11           3           8

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Boston        51   31     28-13 23-18 0.622      33-19      9-7      45-36-1
2  Philadelphia  51   31     24-17 27-14 0.622      32-20      6-10     37-43-2
3  Toronto       48   34     24-17 24-17 0.585      30-22      10-6     47-35-0
4  Brooklyn      44   38     20-21 24-17 0.537      31-21      10-6     33-47-2
5  New York      37   45     17-24 20-21 0.451      22-30      5-11     39-43-0
6  Milwaukee     51   31     27-14 24-17 0.622      33-19      12-4     39-43-0
7  Chicago       46   36     27-14 19-22 0.561      29-23      10-6     42-39-1
8  Cleveland     44   38     25-16 19-22 0.537      27-25      10-6     42-37-3
9  Indiana       25   57     16-25 9-32  0.305      11-41      2-14     37-42-3
10 Detroit       23   59     13-28 10-31 0.280      18-34      6-10     45-37-0
11 Miami         53   29     29-12 24-17 0.646      35-17      13-3     46-35-1
12 Atlanta       43   39     27-14 16-25 0.524      26-26      9-7      37-45-0
13 Charlotte     43   39     22-19 21-20 0.524      27-25      8-8      45-35-2
14 Washington    35   47     21-20 14-27 0.427      24-28      7-9      32-48-2
15 Orlando       22   60     12-29 10-31 0.268      12-40      3-13     37-45-0
16 Utah          49   33     29-12 20-21 0.598      33-19      15-1     33-45-4
17 Denver        48   34     23-18 25-16 0.585      29-23      6-10     36-45-1
18 Minnesota     46   36     26-15 20-21 0.561      32-20      12-4     42-38-2
19 Portland      27   55     17-24 10-31 0.329      11-41      1-15     30-51-1
20 Oklahoma City 24   58     12-29 12-29 0.293      17-35      6-10     48-30-4
21 Phoenix       64   18     32-9  32-9  0.780      39-13      10-6     44-38-0
22 Golden State  53   29     31-10 22-19 0.646      33-19      12-4     41-37-4
23 L.A. Clippers 42   40     25-16 17-24 0.512      26-26      9-7      41-41-0
24 L.A. Lakers   33   49     21-20 12-29 0.402      18-34      3-13     35-46-1
25 Sacramento    30   52     16-25 14-27 0.366      20-32      6-10     39-42-1
26 Memphis       56   26     30-11 26-15 0.683      36-16      11-5     52-29-1
27 Dallas        52   30     29-12 23-18 0.634      36-16      14-2     46-35-1
28 New Orleans   36   46     19-22 17-24 0.439      25-27      6-10     41-40-1
29 San Antonio   34   48     16-25 18-23 0.415      24-28      6-10     44-37-1
30 Houston       20   62     11-30 9-32  0.244      11-41      3-13     35-46-1
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  40-40-2 ⋯ 7          4        3          NA      4        4          NA
2  38-41-3 ⋯ 1          3        4          NA      3        4          NA
3  41-41-0 ⋯ 6          4        3          NA      4        4          NA
4  40-41-1 ⋯ 6          3        4          NA      4        4          NA
5  40-42-0 ⋯ 1          3        4          NA      4        4          NA
6  43-39-0 ⋯ 4          3        4          NA      4        3          NA
7  40-41-1 ⋯ 6          4        3          NA      4        4          NA
8  37-44-1 ⋯ 6          4        3          NA      3        4          NA
9  46-35-1 ⋯ 1          3        4          NA      4        3          NA
10 40-39-3 ⋯ 1          4        3          NA      4        3          NA
11 49-33-0 ⋯ 3          4        3          NA      4        3          NA
12 43-39-0 ⋯ 7          3        4          NA      4        3          NA
13 40-41-1 ⋯ 8          4        3          NA      4        4          NA
14 44-37-1 ⋯ 9          3        4          NA      4        3          NA
15 41-40-1 ⋯ 1          3        4          NA      4        4          NA
16 37-43-2 ⋯ 1          3        4          NA      3        4          NA
17 44-36-2 ⋯ 1          3        4          NA      4        3          NA
18 50-32-0 ⋯ 4          4        3          NA      5        3          NA
19 36-44-2 ⋯ 1          3        5          NA      3        4          NA
20 39-41-2 ⋯ 1          4        3          NA      3        4          NA
21 40-41-1 ⋯ 6          4        3          NA      4        4          NA
22 35-45-2 ⋯ 4          4        3          NA      3        4          NA
23 38-41-3 ⋯ 7          4        4          NA      3        4          NA
24 46-35-1 ⋯ 1          3        4          NA      4        3          NA
25 43-38-1 ⋯ 1          3        4          NA      4        3          NA
26 43-38-1 ⋯ 5          5        2          NA      4        3          NA
27 31-50-1 ⋯ 2          4        3          NA      3        5          NA
28 32-48-2 ⋯ 1          4        4          NA      3        4          NA
29 39-41-2 ⋯ 1          4        3          NA      3        4          NA
30 45-36-1 ⋯ 1          3        4          NA      4        3          NA
   Games_Played Home_Played Away_Played
1  82            3           3
2  82            3           3
3  82            3           3
4  82            4           3
5  82            3           4
6  82            3           3
7  82            3           3
8  82            3           3
9  82            3          12
10 82            3           4
11 82            3           3
12 82            3           3
13 82            3           4
14 82            4           3
15 82            3           4
16 82            3           4
17 82            3           3
18 82            3           4
19 82            3           4
20 82            3           3
21 82           12          12
22 82            4           3
23 82            3           3
24 82            4           3
25 82            3           3
26 82            4           3
27 82            3           3
28 82            3           3
29 82            3           3
30 82            4          12

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Philadelphia  49   23     29-7  20-16 0.681      31-11      10-2     38-31-3
2  Brooklyn      48   24     28-8  20-16 0.667      26-16      8-4      38-34-0
3  New York      41   31     25-11 16-20 0.569      25-17      4-8      45-26-1
4  Boston        36   36     21-15 15-21 0.500      20-22      4-8      33-38-1
5  Toronto       27   45     16-20 11-25 0.375      17-25      4-8      31-40-1
6  Milwaukee     46   26     26-10 20-16 0.639      30-12      11-1     32-40-0
7  Indiana       34   38     13-23 21-15 0.472      20-22      7-5      32-39-1
8  Chicago       31   41     15-21 16-20 0.431      21-21      7-5      38-34-0
9  Cleveland     22   50     13-23 9-27  0.306      16-26      4-8      25-46-1
10 Detroit       20   52     13-23 7-29  0.278      12-30      1-11     35-35-2
11 Atlanta       41   31     25-11 16-20 0.569      24-18      9-3      39-32-1
12 Miami         40   32     21-15 19-17 0.556      24-18      6-6      34-36-2
13 Washington    34   38     19-17 15-21 0.472      16-26      3-9      41-30-1
14 Charlotte     33   39     18-18 15-21 0.458      20-22      8-4      36-35-1
15 Orlando       21   51     11-25 10-26 0.292      13-29      4-8      32-38-2
16 Utah          52   20     31-5  21-15 0.722      28-14      7-5      41-31-0
17 Denver        47   25     25-11 22-14 0.653      26-16      9-3      34-38-0
18 Portland      42   30     20-16 22-14 0.583      23-19      6-6      38-34-0
19 Minnesota     23   49     13-23 10-26 0.319      15-27      5-7      33-36-3
20 Oklahoma City 22   50     10-26 12-24 0.306      12-30      3-9      31-40-1
21 Phoenix       51   21     27-9  24-12 0.708      30-12      7-5      42-28-2
22 L.A. Clippers 47   25     26-10 21-15 0.653      27-15      9-3      39-32-1
23 L.A. Lakers   42   30     21-15 21-15 0.583      25-17      4-8      32-39-1
24 Golden State  39   33     25-11 14-22 0.542      25-17      5-7      37-35-0
25 Sacramento    31   41     16-20 15-21 0.431      18-24      5-7      34-37-1
26 Dallas        42   30     21-15 21-15 0.583      21-21      7-5      35-37-0
27 Memphis       38   34     18-18 20-16 0.528      19-23      6-6      42-30-0
28 San Antonio   33   39     14-22 19-17 0.458      17-25      6-6      38-32-2
29 New Orleans   31   41     18-18 13-23 0.431      18-24      6-6      34-38-0
30 Houston       17   55     9-27  8-28  0.236      11-31      5-7      27-45-0
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  34-38-0 ⋯ 2          3        3          NA      3        3          NA
2  40-32-0 ⋯ 4          3        3          NA      4        3          NA
3  32-40-0 ⋯ 8          4        2          NA      3        4          NA
4  37-35-0 ⋯ 8          3        3          NA      3        3          NA
5  38-34-0 ⋯ 8          3        4          NA      3        3          NA
6  41-30-1 ⋯ 1          3        4          NA      4        3          NA
7  44-27-1 ⋯ 5          3        3          NA      4        2          NA
8  32-40-0 ⋯ 5          3        3          NA      3        4          NA
9  32-38-2 ⋯ 8          2        4          NA      3        3          NA
10 32-39-1 ⋯ 1          3        3          NA      3        3          NA
11 35-37-0 ⋯ 3          3        3          NA      3        3          NA
12 38-34-0 ⋯ 6          3        3          NA      3        3          NA
13 36-36-0 ⋯ 9          4        3          NA      3        3          NA
14 31-40-1 ⋯ 4          3        3          NA      3        4          NA
15 39-32-1 ⋯ 8          3        3          NA      3        3          NA
16 33-38-1 ⋯ 5          4        3          NA      3        3          NA
17 39-33-0 ⋯ 3          3        3          NA      3        3          NA
18 38-34-0 ⋯ 6          3        3          NA      3        3          NA
19 37-35-0 ⋯ 7          3        3          NA      3        3          NA
20 36-36-0 ⋯ 9          3        4          NA      3        3          NA
21 42-30-0 ⋯ 5          4        2          NA      4        3          NA
22 35-35-2 ⋯ 3          3        3          NA      3        3          NA
23 28-43-1 ⋯ 8          3        3          NA      2        4          NA
24 30-42-0 ⋯ 7          3        3          NA      3        4          NA
25 35-37-0 ⋯ 7          3        3          NA      3        3          NA
26 34-38-0 ⋯ 5          3        3          NA      3        3          NA
27 36-36-0 ⋯ 6          4        3          NA      3        3          NA
28 36-36-0 ⋯ 6          3        3          NA      3        3          NA
29 42-30-0 ⋯ 6          3        3          NA      4        3          NA
30 34-37-1 ⋯ 7          2        4          NA      3        3          NA
   Games_Played Home_Played Away_Played
1  72            9           3
2  72           10           3
3  72            3           3
4  72            3           3
5  72            3           3
6  72            3           3
7  72            3           3
8  72            3           3
9  72            3          11
10 72            3           9
11 72            3           3
12 72            3           2
13 72            2           3
14 72            2           3
15 72            3           3
16 72            8           3
17 72            3           3
18 72            3           3
19 72            3           3
20 72            3           3
21 72           11           3
22 72            3           3
23 72            3           3
24 72            3           3
25 72            3           3
26 72            3           3
27 72            2           3
28 72            3           2
29 72            2           3
30 72           11          10

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Toronto       53   19     26-10 27-9  0.736      34-11      9-5      41-30-1
2  Boston        48   24     26-10 22-14 0.667      30-13      9-6      41-27-4
3  Philadelphia  43   30     31-4  12-26 0.589      28-18      11-5     31-38-4
4  Brooklyn      35   37     20-16 15-21 0.486      23-23      6-10     37-35-0
5  New York      21   45     11-22 10-23 0.318      15-28      2-11     35-30-1
6  Milwaukee     56   17     30-5  26-12 0.767      37-7       13-1     39-34-0
7  Indiana       45   28     25-11 20-17 0.616      28-19      8-7      40-30-3
8  Chicago       22   43     14-20 8-23  0.338      15-28      7-9      29-35-1
9  Detroit       20   46     11-22 9-24  0.303      12-31      5-10     26-39-1
10 Cleveland     19   46     11-25 8-21  0.292      12-32      4-10     29-34-2
11 Miami         44   29     29-7  15-22 0.603      30-13      10-4     36-35-2
12 Orlando       33   40     18-17 15-23 0.452      20-23      9-5      35-36-2
13 Charlotte     23   42     10-21 13-21 0.354      16-24      2-7      34-30-1
14 Washington    25   47     16-20 9-27  0.347      18-27      5-9      34-36-2
15 Atlanta       20   47     14-20 6-27  0.299      11-32      6-7      29-36-2
16 Denver        46   27     26-11 20-16 0.630      29-16      12-2     33-36-4
17 Oklahoma City 44   28     23-14 21-14 0.611      27-19      8-5      44-28-0
18 Utah          44   28     23-12 21-16 0.611      24-21      5-7      34-36-2
19 Portland      35   39     21-15 14-24 0.473      20-27      5-8      32-39-3
20 Minnesota     19   45     8-24  11-21 0.297      9-30       2-10     23-39-2
21 L.A. Lakers   52   19     25-10 27-9  0.732      36-10      10-3     36-34-1
22 L.A. Clippers 49   23     27-9  22-14 0.681      32-16      8-6      41-31-0
23 Phoenix       34   39     17-22 17-17 0.466      19-27      6-9      37-35-1
24 Sacramento    31   41     16-19 15-22 0.431      23-23      8-5      37-33-2
25 Golden State  15   50     8-26  7-24  0.231      9-34       2-11     31-34-0
26 Houston       44   28     24-12 20-16 0.611      28-19      8-5      33-39-0
27 Dallas        43   32     20-18 23-14 0.573      27-20      10-4     37-35-3
28 Memphis       34   39     20-17 14-22 0.466      20-26      4-9      36-36-1
29 San Antonio   32   39     19-15 13-24 0.451      20-23      7-6      30-40-1
30 New Orleans   30   42     15-21 15-21 0.417      18-30      4-9      35-35-2
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  36-35-1 ⋯ 5          4        3          NA      3        3          NA
2  34-37-1 ⋯ 6          4        2          NA      3        3          NA
3  39-33-1 ⋯ 5          3        3          NA      3        3          NA
4  36-35-1 ⋯ 1          3        3          NA      3        3          NA
5  31-34-1 ⋯ 1          3        3          NA      3        3          NA
6  35-37-1 ⋯ 1          3        3          NA      3        3          NA
7  38-34-1 ⋯ 7          4        3          NA      3        3          NA
8  34-31-0 ⋯ 9          2        3          NA      3        3          NA
9  39-26-1 ⋯ 1          2        3          NA      3        2          NA
10 36-29-0 ⋯ 1          2        3          NA      3        2          NA
11 43-28-2 ⋯ 4          3        3          NA      4        2          NA
12 38-32-3 ⋯ 5          3        3          NA      3        3          NA
13 31-34-0 ⋯ 7          3        3          NA      3        3          NA
14 40-31-1 ⋯ 9          3        3          NA      4        3          NA
15 40-27-0 ⋯ 7          2        3          NA      4        2          NA
16 38-34-1 ⋯ 2          3        3          NA      3        3          NA
17 34-37-1 ⋯ 5          4        2          NA      3        3          NA
18 38-34-0 ⋯ 7          3        3          NA      3        3          NA
19 44-30-0 ⋯ 8          3        3          NA      4        3          NA
20 36-28-0 ⋯ 1          2        3          NA      3        2          NA
21 34-37-0 ⋯ 3          3        3          NA      3        3          NA
22 34-37-1 ⋯ 6          4        3          NA      3        3          NA
23 38-35-0 ⋯ 9          3        3          NA      3        3          NA
24 39-33-0 ⋯ 5          3        3          NA      3        3          NA
25 30-35-0 ⋯ 1          3        3          NA      3        3          NA
26 30-42-0 ⋯ 5          3        3          NA      3        4          NA
27 45-30-0 ⋯ 4          3        3          NA      4        3          NA
28 32-41-0 ⋯ 9          3        3          NA      3        4          NA
29 42-28-1 ⋯ 6          3        4          NA      4        2          NA
30 38-34-0 ⋯ 9          3        3          NA      3        3          NA
   Games_Played Home_Played Away_Played
1  72            3          11
2  72            3           3
3  73            7           3
4  72            3           3
5  66            3           3
6  73            8           3
7  73            3           3
8  65            3          10
9  66            3          11
10 65            3          10
11 73            9           3
12 73            2           3
13 65            3           3
14 72            3          11
15 67            3           8
16 73            3           3
17 72            3           3
18 72            3           3
19 74            3           3
20 64           10           3
21 71            3          11
22 72           11           3
23 73            3           2
24 72            2           3
25 65           10           9
26 72            3           3
27 75            3           3
28 73            3           3
29 71            2           3
30 72            3           3

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Toronto       58   24     32-9  26-15 0.707      36-16      12-4     38-44-0
2  Philadelphia  51   31     31-10 20-21 0.622      31-21      8-8      38-44-0
3  Boston        49   33     28-13 21-20 0.598      35-17      10-6     39-42-1
4  Brooklyn      42   40     23-18 19-22 0.512      29-23      8-8      45-37-0
5  New York      17   65     9-32  8-33  0.207      11-41      2-14     32-49-1
6  Milwaukee     60   22     33-8  27-14 0.732      40-12      14-2     47-31-4
7  Indiana       48   34     29-12 19-22 0.585      33-19      11-5     41-41-0
8  Detroit       41   41     26-15 15-26 0.500      27-25      8-8      41-38-3
9  Chicago       22   60     9-32  13-28 0.268      16-36      3-13     35-46-1
10 Cleveland     19   63     13-28 6-35  0.232      15-37      4-12     37-43-2
11 Orlando       42   40     25-16 17-24 0.512      30-22      10-6     45-36-1
12 Charlotte     39   43     25-16 14-27 0.476      29-23      10-6     40-41-1
13 Miami         39   43     19-22 20-21 0.476      23-29      7-9      43-38-1
14 Washington    32   50     22-19 10-31 0.390      19-33      7-9      38-44-0
15 Atlanta       29   53     17-24 12-29 0.354      16-36      6-10     42-40-0
16 Denver        54   28     34-7  20-21 0.659      34-18      12-4     42-40-0
17 Portland      53   29     32-9  21-20 0.646      29-23      6-10     45-36-1
18 Utah          50   32     29-12 21-20 0.610      30-22      8-8      44-36-2
19 Oklahoma City 49   33     27-14 22-19 0.598      28-24      9-7      42-40-0
20 Minnesota     36   46     25-16 11-30 0.439      22-30      5-11     40-42-0
21 Golden State  57   25     30-11 27-14 0.695      35-17      13-3     35-46-1
22 L.A. Clippers 48   34     26-15 22-19 0.585      28-24      11-5     45-36-1
23 Sacramento    39   43     24-17 15-26 0.476      21-31      4-12     45-36-1
24 L.A. Lakers   37   45     22-19 15-26 0.451      25-27      9-7      35-45-2
25 Phoenix       19   63     12-29 7-34  0.232      11-41      3-13     36-46-0
26 Houston       53   29     31-10 22-19 0.646      32-20      10-6     40-39-3
27 San Antonio   48   34     32-9  16-25 0.585      30-22      10-6     43-37-2
28 Memphis       33   49     21-20 12-29 0.402      24-28      8-8      39-43-0
29 New Orleans   33   49     19-22 14-27 0.402      23-29      8-8      37-44-1
30 Dallas        33   49     24-17 9-32  0.402      18-34      4-12     45-34-3
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  44-35-3 ⋯ 4          3        4          NA      4        3          NA
2  43-39-0 ⋯ 8          3        4          NA      4        3          NA
3  47-35-0 ⋯ 6          3        4          NA      4        3          NA
4  41-41-0 ⋯ 8          4        3          NA      4        4          NA
5  37-44-1 ⋯ 1          3        4          NA      3        4          NA
6  42-40-0 ⋯ 2          4        3          NA      4        4          NA
7  36-46-0 ⋯ 5          4        4          NA      3        4          NA
8  39-43-0 ⋯ 8          4        3          NA      3        4          NA
9  38-41-3 ⋯ 1          3        4          NA      3        4          NA
10 44-37-1 ⋯ 1          3        4          NA      4        3          NA
11 38-44-0 ⋯ 6          4        3          NA      3        4          NA
12 44-36-2 ⋯ 6          4        4          NA      4        3          NA
13 42-40-0 ⋯ 9          4        3          NA      4        4          NA
14 50-32-0 ⋯ 9          3        4          NA      5        3          NA
15 47-35-0 ⋯ 1          4        4          NA      4        3          NA
16 34-47-1 ⋯ 4          4        4          NA      3        4          NA
17 43-37-2 ⋯ 1          4        3          NA      4        3          NA
18 39-42-1 ⋯ 8          4        3          NA      3        4          NA
19 40-41-1 ⋯ 7          4        4          NA      4        4          NA
20 44-38-0 ⋯ 1          4        4          NA      4        3          NA
21 38-44-0 ⋯ 3          3        4          NA      3        4          NA
22 45-36-1 ⋯ 5          4        3          NA      4        3          NA
23 41-40-1 ⋯ 1          4        3          NA      4        4          NA
24 32-49-1 ⋯ 7          3        4          NA      3        4          NA
25 38-44-0 ⋯ 1          3        4          NA      3        4          NA
26 39-41-2 ⋯ 6          4        3          NA      3        4          NA
27 43-38-1 ⋯ 6          4        3          NA      4        3          NA
28 37-44-1 ⋯ 8          3        4          NA      3        4          NA
29 44-37-1 ⋯ 8          3        4          NA      4        3          NA
30 37-44-1 ⋯ 1          4        3          NA      3        4          NA
   Games_Played Home_Played Away_Played
1  82           12           3
2  82            4           4
3  82            3           4
4  82            3           3
5  82           12          11
6  82           11           3
7  82            3           3
8  82            3           3
9  82           12           3
10 82            3           9
11 82            3           3
12 82            3           3
13 82            3           4
14 82            3           4
15 82            3           3
16 82           10           4
17 82           12           4
18 82            3           4
19 82            3           3
20 82            3           4
21 82            4           3
22 82            3           3
23 82            3           3
24 82            3           3
25 82            3          10
26 82            4           3
27 82           12           3
28 82            4           3
29 82            3           3
30 82            3          12

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Toronto       59   23     34-7  25-16 0.720      40-12      12-4     43-38-1
2  Boston        55   27     27-14 28-13 0.671      33-19      12-4     50-30-2
3  Philadelphia  52   30     30-11 22-19 0.634      34-18      9-7      47-33-2
4  New York      29   53     19-22 10-31 0.354      17-35      6-10     38-44-0
5  Brooklyn      28   54     15-26 13-28 0.341      19-33      1-15     46-36-0
6  Cleveland     50   32     29-12 21-20 0.610      35-17      11-5     32-49-1
7  Indiana       48   34     27-14 21-20 0.585      32-20      10-6     47-35-0
8  Milwaukee     44   38     25-16 19-22 0.537      27-25      6-10     34-43-5
9  Detroit       39   43     25-16 14-27 0.476      24-28      9-7      40-40-2
10 Chicago       27   55     17-24 10-31 0.329      21-31      4-12     41-40-1
11 Miami         44   38     26-15 18-23 0.537      31-21      11-5     40-36-6
12 Washington    43   39     23-18 20-21 0.524      28-24      8-8      37-44-1
13 Charlotte     36   46     21-20 15-26 0.439      22-30      11-5     34-44-4
14 Orlando       25   57     17-24 8-33  0.305      15-37      5-11     37-43-2
15 Atlanta       24   58     16-25 8-33  0.293      12-40      5-11     40-39-3
16 Portland      49   33     28-13 21-20 0.598      31-21      9-7      45-32-5
17 Oklahoma City 48   34     27-14 21-20 0.585      28-24      5-11     34-47-1
18 Utah          48   34     28-13 20-21 0.585      34-18      7-9      43-39-0
19 Minnesota     47   35     30-11 17-24 0.573      34-18      10-6     37-42-3
20 Denver        46   36     31-10 15-26 0.561      28-24      9-7      37-42-3
21 Golden State  58   24     29-12 29-12 0.707      34-18      13-3     34-47-1
22 L.A. Clippers 42   40     22-19 20-21 0.512      24-28      12-4     42-39-1
23 L.A. Lakers   35   47     20-21 15-26 0.427      19-33      6-10     43-39-0
24 Sacramento    27   55     14-27 13-28 0.329      14-38      5-11     39-40-3
25 Phoenix       21   61     10-31 11-30 0.256      15-37      4-12     37-43-2
26 Houston       65   17     34-7  31-10 0.793      41-11      12-4     41-40-1
27 New Orleans   48   34     24-17 24-17 0.585      27-25      9-7      45-36-1
28 San Antonio   47   35     33-8  14-27 0.573      29-23      9-7      42-38-2
29 Dallas        24   58     15-26 9-32  0.293      14-38      5-11     41-40-1
30 Memphis       22   60     16-25 6-35  0.268      18-34      5-11     36-44-2
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  41-40-1 ⋯ 4          4        3          NA      4        4          NA
2  43-38-1 ⋯ 4          5        3          NA      4        3          NA
3  41-40-1 ⋯ 7          4        3          NA      4        4          NA
4  43-38-1 ⋯ 1          3        4          NA      4        3          NA
5  37-43-2 ⋯ 1          4        3          NA      3        4          NA
6  39-41-2 ⋯ 5          3        4          NA      3        4          NA
7  32-49-1 ⋯ 6          4        3          NA      3        4          NA
8  46-35-1 ⋯ 1          3        4          NA      4        3          NA
9  34-44-4 ⋯ 7          4        4          NA      3        4          NA
10 43-38-1 ⋯ 1          4        4          NA      4        3          NA
11 37-44-1 ⋯ 5          4        3          NA      3        4          NA
12 36-44-2 ⋯ 8          3        4          NA      3        4          NA
13 41-40-1 ⋯ 5          3        4          NA      4        4          NA
14 34-48-0 ⋯ 1          3        4          NA      3        4          NA
15 37-44-1 ⋯ 1          4        3          NA      3        4          NA
16 35-47-0 ⋯ 7          4        3          NA      3        4          NA
17 36-46-0 ⋯ 1          3        4          NA      3        4          NA
18 39-42-1 ⋯ 9          4        3          NA      3        4          NA
19 45-36-1 ⋯ 6          3        4          NA      4        3          NA
20 42-39-1 ⋯ 7          3        4          NA      4        3          NA
21 39-43-0 ⋯ 3          3        4          NA      3        4          NA
22 43-38-1 ⋯ 4          4        3          NA      4        3          NA
23 42-38-2 ⋯ 1          4        3          NA      4        3          NA
24 39-42-1 ⋯ 1          3        4          NA      3        4          NA
25 38-44-0 ⋯ 1          3        4          NA      3        4          NA
26 33-48-1 ⋯ 4          4        4          NA      3        4          NA
27 47-35-0 ⋯ 7          4        3          NA      4        3          NA
28 38-44-0 ⋯ 7          4        3          NA      3        4          NA
29 37-44-1 ⋯ 1          4        4          NA      3        4          NA
30 39-42-1 ⋯ 1          3        4          NA      3        4          NA
   Games_Played Home_Played Away_Played
1  82           10           3
2  82            3           3
3  82            4           3
4  82            3           4
5  82            3           3
6  82            3           4
7  82            3           4
8  82            3           3
9  82            3           3
10 82            3           4
11 82            3           3
12 82            3           4
13 82            4           3
14 82            3          11
15 82            3          11
16 82            3           4
17 82            3           4
18 82            3           4
19 82            4           3
20 82            4           3
21 82            3           3
22 82            3           4
23 82            4           3
24 82            3           3
25 82            4           4
26 82           10           4
27 82            3           3
28 82           11           3
29 82            3          12
30 82            3           9

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Boston        53   29     30-11 23-18 0.646      36-16      11-5     40-40-2
2  Toronto       51   31     28-13 23-18 0.622      34-18      14-2     45-36-1
3  New York      31   51     19-22 12-29 0.378      22-30      5-11     42-40-0
4  Philadelphia  28   54     17-24 11-30 0.341      19-33      7-9      49-33-0
5  Brooklyn      20   62     13-28 7-34  0.244      11-41      3-13     41-38-3
6  Cleveland     51   31     31-10 20-21 0.622      35-17      8-8      36-43-3
7  Milwaukee     42   40     23-18 19-22 0.512      27-25      10-6     36-46-0
8  Indiana       42   40     29-12 13-28 0.512      26-26      8-8      39-42-1
9  Chicago       41   41     25-16 16-25 0.500      28-24      9-7      42-40-0
10 Detroit       37   45     24-17 13-28 0.451      21-31      5-11     38-44-0
11 Washington    49   33     30-11 19-22 0.598      32-20      8-8      42-39-1
12 Atlanta       43   39     23-18 20-21 0.524      30-22      6-10     39-43-0
13 Miami         41   41     23-18 18-23 0.500      27-25      9-7      48-33-1
14 Charlotte     36   46     22-19 14-27 0.439      22-30      10-6     35-44-3
15 Orlando       29   53     16-25 13-28 0.354      20-32      7-9      32-49-1
16 Utah          51   31     29-12 22-19 0.622      31-21      8-8      36-42-4
17 Oklahoma City 47   35     28-13 19-22 0.573      29-23      10-6     45-36-1
18 Portland      41   41     25-16 16-25 0.500      28-24      11-5     40-42-0
19 Denver        40   42     22-19 18-23 0.488      24-28      6-10     46-36-0
20 Minnesota     31   51     20-21 11-30 0.378      18-34      5-11     37-44-1
21 Golden State  67   15     36-5  31-10 0.817      42-10      14-2     40-39-3
22 L.A. Clippers 51   31     29-12 22-19 0.622      31-21      10-6     40-41-1
23 Sacramento    32   50     17-24 15-26 0.390      21-31      7-9      41-38-3
24 L.A. Lakers   26   56     17-24 9-32  0.317      16-36      6-10     37-43-2
25 Phoenix       24   58     15-26 9-32  0.293      11-41      3-13     40-41-1
26 San Antonio   61   21     31-10 30-11 0.744      36-16      11-5     41-39-2
27 Houston       55   27     30-11 25-16 0.671      36-16      10-6     42-40-0
28 Memphis       43   39     24-17 19-22 0.524      28-24      8-8      41-41-0
29 New Orleans   34   48     21-20 13-28 0.415      20-32      6-10     39-42-1
30 Dallas        33   49     21-20 12-29 0.402      19-33      5-11     43-38-1
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  39-39-4 ⋯ 5          4        4          NA      3        3          NA
2  44-38-0 ⋯ 2          4        3          NA      4        3          NA
3  38-42-2 ⋯ 1          4        4          NA      3        4          NA
4  42-39-1 ⋯ 9          4        3          NA      4        3          NA
5  39-40-3 ⋯ 1          4        3          NA      3        4          NA
6  47-34-1 ⋯ 8          3        4          NA      4        3          NA
7  41-39-2 ⋯ 6          3        4          NA      4        3          NA
8  41-41-0 ⋯ 8          3        4          NA      4        4          NA
9  32-49-1 ⋯ 7          4        4          NA      3        4          NA
10 36-45-1 ⋯ 1          3        4          NA      3        4          NA
11 51-31-0 ⋯ 8          4        3          NA      5        3          NA
12 32-48-2 ⋯ 1          3        4          NA      3        4          NA
13 38-44-0 ⋯ 7          4        3          NA      3        4          NA
14 44-38-0 ⋯ 6          3        4          NA      4        3          NA
15 39-42-1 ⋯ 9          3        4          NA      3        4          NA
16 42-40-0 ⋯ 8          3        4          NA      4        4          NA
17 37-44-1 ⋯ 6          4        3          NA      3        4          NA
18 44-37-1 ⋯ 5          4        4          NA      4        3          NA
19 50-31-1 ⋯ 1          4        3          NA      5        3          NA
20 44-38-0 ⋯ 1          3        4          NA      4        3          NA
21 32-50-0 ⋯ 2          4        3          NA      3        5          NA
22 44-37-1 ⋯ 6          4        4          NA      4        3          NA
23 35-47-0 ⋯ 9          4        3          NA      3        4          NA
24 44-37-1 ⋯ 1          3        4          NA      4        3          NA
25 50-32-0 ⋯ 1          4        4          NA      5        3          NA
26 43-37-2 ⋯ 5          4        3          NA      4        3          NA
27 41-40-1 ⋯ 6          4        4          NA      4        4          NA
28 38-41-3 ⋯ 8          4        4          NA      3        4          NA
29 37-44-1 ⋯ 1          3        4          NA      3        4          NA
30 34-46-2 ⋯ 1          4        3          NA      3        4          NA
   Games_Played Home_Played Away_Played
1  82           4            3
2  82           3            3
3  82           3            3
4  82           3            4
5  82           3           10
6  82           4            4
7  82           3            3
8  82           3            3
9  82           3            3
10 82           3            3
11 82           4            3
12 82           3            4
13 82           3            3
14 82           3            3
15 82           3            3
16 82           3            3
17 82           3            3
18 82           3            3
19 82           3            3
20 82           4            4
21 82           8            4
22 82           3            3
23 82           3            3
24 82           3           12
25 82           3           12
26 82           4            4
27 82           4            3
28 82           3            3
29 82           4            3
30 82           4            3

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Toronto       56   26     32-9  24-17 0.683      39-13      14-2     45-37-0
2  Boston        48   34     28-13 20-21 0.585      31-21      10-6     42-39-1
3  New York      32   50     18-23 14-27 0.390      21-31      8-8      44-38-0
4  Brooklyn      21   61     14-27 7-34  0.256      12-40      6-10     38-43-1
5  Philadelphia  10   72     7-34  3-38  0.122      3-49       2-14     37-44-1
6  Cleveland     57   25     33-8  24-17 0.695      35-17      8-8      37-42-3
7  Indiana       45   37     26-15 19-22 0.549      30-22      8-8      41-40-1
8  Detroit       44   38     26-15 18-23 0.537      29-23      10-6     42-38-2
9  Chicago       42   40     26-15 16-25 0.512      25-27      10-6     36-46-0
10 Milwaukee     33   49     23-18 10-31 0.402      21-31      4-12     38-43-1
11 Miami         48   34     28-13 20-21 0.585      31-21      10-6     43-38-1
12 Atlanta       48   34     27-14 21-20 0.585      29-23      8-8      42-39-1
13 Charlotte     48   34     30-11 18-23 0.585      33-19      8-8      42-39-1
14 Washington    41   41     22-19 19-22 0.500      30-22      10-6     43-39-0
15 Orlando       35   47     23-18 12-29 0.427      21-31      4-12     45-36-1
16 Oklahoma City 55   27     32-9  23-18 0.671      37-15      13-3     37-44-1
17 Portland      44   38     28-13 16-25 0.537      29-23      11-5     44-38-0
18 Utah          40   42     24-17 16-25 0.488      24-28      8-8      41-41-0
19 Denver        33   49     18-23 15-26 0.402      18-34      4-12     42-38-2
20 Minnesota     29   53     14-27 15-26 0.354      18-34      4-12     39-42-1
21 Golden State  73    9     39-2  34-7  0.890      46-6       15-1     45-35-2
22 L.A. Clippers 53   29     29-12 24-17 0.646      31-21      9-7      40-39-3
23 Sacramento    33   49     18-23 15-26 0.402      19-33      8-8      38-43-1
24 Phoenix       23   59     14-27 9-32  0.280      17-35      6-10     36-46-0
25 L.A. Lakers   17   65     12-29 5-36  0.207      8-44       2-14     36-46-0
26 San Antonio   67   15     40-1  27-14 0.817      43-9       14-2     44-38-0
27 Dallas        42   40     23-18 19-22 0.512      27-25      7-9      45-36-1
28 Memphis       42   40     26-15 16-25 0.512      25-27      7-9      42-39-1
29 Houston       41   41     23-18 18-23 0.500      28-24      8-8      37-45-0
30 New Orleans   30   52     21-20 9-32  0.366      20-32      4-12     36-46-0
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  42-39-1 ⋯ 2          4        3          NA      4        3          NA
2  39-43-0 ⋯ 6          4        3          NA      3        4          NA
3  34-47-1 ⋯ 8          4        3          NA      3        4          NA
4  41-41-0 ⋯ 1          3        4          NA      4        4          NA
5  43-38-1 ⋯ 1          3        4          NA      4        3          NA
6  41-41-0 ⋯ 8          3        4          NA      4        4          NA
7  37-45-0 ⋯ 8          4        4          NA      3        4          NA
8  42-40-0 ⋯ 6          4        3          NA      4        4          NA
9  39-41-2 ⋯ 6          3        4          NA      3        4          NA
10 40-42-0 ⋯ 1          3        4          NA      4        4          NA
11 34-47-1 ⋯ 6          4        3          NA      3        4          NA
12 38-44-0 ⋯ 8          4        3          NA      3        4          NA
13 40-40-2 ⋯ 8          4        3          NA      4        4          NA
14 43-37-2 ⋯ 6          4        3          NA      4        3          NA
15 42-40-0 ⋯ 1          4        3          NA      4        4          NA
16 39-43-0 ⋯ 3          3        4          NA      3        4          NA
17 44-38-0 ⋯ 5          4        3          NA      4        3          NA
18 33-47-2 ⋯ 8          4        4          NA      3        4          NA
19 46-35-1 ⋯ 1          4        3          NA      4        3          NA
20 45-36-1 ⋯ 1          3        4          NA      4        3          NA
21 45-36-1 ⋯ 1          4        3          NA      4        3          NA
22 34-48-0 ⋯ 7          4        3          NA      3        4          NA
23 40-41-1 ⋯ 8          3        4          NA      4        4          NA
24 39-42-1 ⋯ 1          3        4          NA      3        4          NA
25 37-44-1 ⋯ 1          3        4          NA      3        4          NA
26 35-45-2 ⋯ 2          4        3          NA      3        4          NA
27 39-42-1 ⋯ 9          4        3          NA      3        4          NA
28 45-35-2 ⋯ 9          4        3          NA      4        3          NA
29 47-35-0 ⋯ 8          3        4          NA      4        3          NA
30 43-38-1 ⋯ 1          3        4          NA      4        3          NA
   Games_Played Home_Played Away_Played
1  82           12           3
2  82            3           4
3  82            3           3
4  82            3          10
5  82           10           6
6  82           11           3
7  82            3           3
8  82            3           3
9  82            3           3
10 82            3           4
11 82            3           4
12 82            3           4
13 82            4           3
14 82            3           3
15 82            3           3
16 82           12           3
17 82            3           3
18 82            3           3
19 82            3           3
20 82            3           3
21 82            5          10
22 82            3           3
23 82            3           3
24 82            3          12
25 82            3           8
26 82            5           3
27 82            3           3
28 82            3           3
29 82            3           3
30 82            4          12

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Toronto       49   33     27-14 22-19 0.598      33-19      11-5     37-44-1
2  Boston        40   42     21-20 19-22 0.488      28-24      12-4     49-32-1
3  Brooklyn      38   44     19-22 19-22 0.463      24-28      10-6     39-41-2
4  Philadelphia  18   64     12-29 6-35  0.220      12-40      2-14     40-40-2
5  New York      17   65     10-31 7-34  0.207      11-41      5-11     33-46-3
6  Cleveland     53   29     31-10 22-19 0.646      35-17      11-5     39-43-0
7  Chicago       50   32     27-14 23-18 0.610      33-19      8-8      39-43-0
8  Milwaukee     41   41     23-18 18-23 0.500      30-22      7-9      46-35-1
9  Indiana       38   44     23-18 15-26 0.463      28-24      8-8      42-37-3
10 Detroit       32   50     18-23 14-27 0.390      23-29      6-10     42-40-0
11 Atlanta       60   22     35-6  25-16 0.732      38-14      12-4     50-30-2
12 Washington    46   36     29-12 17-24 0.561      30-22      10-6     33-46-3
13 Miami         37   45     20-21 17-24 0.451      25-27      6-10     35-43-4
14 Charlotte     33   49     19-22 14-27 0.402      25-27      8-8      39-41-2
15 Orlando       25   57     13-28 12-29 0.305      15-37      4-12     41-40-1
16 Portland      51   31     32-9  19-22 0.622      31-21      11-5     40-41-1
17 Oklahoma City 45   37     29-12 16-25 0.549      25-27      10-6     39-41-2
18 Utah          38   44     21-20 17-24 0.463      23-29      9-7      44-35-3
19 Denver        30   52     19-22 11-30 0.366      19-33      6-10     36-43-3
20 Minnesota     16   66     9-32  7-34  0.195      7-45       4-12     35-46-1
21 Golden State  67   15     39-2  28-13 0.817      42-10      13-3     47-34-1
22 L.A. Clippers 56   26     30-11 26-15 0.683      37-15      12-4     37-44-1
23 Phoenix       39   43     22-19 17-24 0.476      21-31      6-10     42-37-3
24 Sacramento    29   53     18-23 11-30 0.354      18-34      7-9      33-46-3
25 L.A. Lakers   21   61     12-29 9-32  0.256      9-43       2-14     36-41-5
26 Houston       56   26     30-11 26-15 0.683      33-19      8-8      48-34-0
27 Memphis       55   27     31-10 24-17 0.671      35-17      9-7      40-40-2
28 San Antonio   55   27     33-8  22-19 0.671      32-20      8-8      41-39-2
29 Dallas        50   32     27-14 23-18 0.610      29-23      7-9      36-44-2
30 New Orleans   45   37     28-13 17-24 0.549      29-23      8-8      45-37-0
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  45-37-0 ⋯ 5          3        4          NA      4        3          NA
2  42-39-1 ⋯ 4          4        3          NA      4        3          NA
3  37-45-0 ⋯ 6          3        4          NA      3        4          NA
4  36-46-0 ⋯ 1          4        4          NA      3        4          NA
5  38-43-1 ⋯ 1          3        4          NA      3        4          NA
6  33-48-1 ⋯ 5          3        4          NA      3        4          NA
7  41-40-1 ⋯ 8          3        4          NA      4        4          NA
8  37-45-0 ⋯ 9          4        3          NA      3        4          NA
9  45-36-1 ⋯ 8          4        3          NA      4        3          NA
10 39-40-3 ⋯ 1          4        4          NA      3        4          NA
11 42-40-0 ⋯ 4          5        3          NA      4        4          NA
12 38-42-2 ⋯ 6          3        4          NA      3        4          NA
13 36-46-0 ⋯ 1          3        4          NA      3        4          NA
14 38-43-1 ⋯ 8          3        4          NA      3        4          NA
15 37-44-1 ⋯ 1          4        4          NA      3        4          NA
16 39-42-1 ⋯ 5          4        4          NA      3        4          NA
17 39-42-1 ⋯ 6          3        4          NA      3        4          NA
18 35-47-0 ⋯ 7          4        3          NA      3        4          NA
19 37-42-3 ⋯ 1          3        4          NA      3        4          NA
20 44-36-2 ⋯ 1          3        4          NA      4        3          NA
21 39-43-0 ⋯ 3          4        3          NA      3        4          NA
22 36-43-3 ⋯ 4          3        4          NA      3        4          NA
23 37-44-1 ⋯ 1          4        3          NA      3        4          NA
24 45-37-0 ⋯ 9          3        4          NA      4        3          NA
25 38-42-2 ⋯ 1          3        4          NA      3        4          NA
26 40-42-0 ⋯ 8          4        3          NA      4        4          NA
27 34-46-2 ⋯ 7          4        4          NA      3        4          NA
28 39-43-0 ⋯ 8          4        3          NA      3        4          NA
29 38-43-1 ⋯ 9          3        4          NA      3        4          NA
30 42-40-0 ⋯ 8          4        3          NA      4        4          NA
   Games_Played Home_Played Away_Played
1  82            3           3
2  82            4           3
3  82            3           3
4  82            3           9
5  82            4          10
6  82            4           3
7  82            3           3
8  82            3           3
9  82            3           3
10 82            3           3
11 82            9           3
12 82            3           3
13 82            4           3
14 82            3           3
15 82            3           3
16 82           12           3
17 82            3           3
18 82            4           3
19 82            3           4
20 82           12          10
21 82            5           3
22 82            4           3
23 82            3           3
24 82            3           4
25 82            3          12
26 82            4           3
27 82            4           3
28 82           11           3
29 82            3           3
30 82            3           3

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  Toronto       48   34     26-15 22-19 0.585      32-20      11-5     46-33-3
2  Brooklyn      44   38     28-13 16-25 0.537      26-26      9-7      42-40-0
3  New York      37   45     19-22 18-23 0.451      26-26      10-6     38-44-0
4  Boston        25   57     16-25 9-32  0.305      21-31      5-11     39-41-2
5  Philadelphia  19   63     10-31 9-32  0.232      14-38      5-11     36-46-0
6  Indiana       56   26     35-6  21-20 0.683      38-14      12-4     38-43-1
7  Chicago       48   34     27-14 21-20 0.585      35-17      11-5     41-40-1
8  Cleveland     33   49     19-22 14-27 0.402      21-31      7-9      40-42-0
9  Detroit       29   53     17-24 12-29 0.354      23-29      6-10     35-46-1
10 Milwaukee     15   67     10-31 5-36  0.183      12-40      4-12     36-45-1
11 Miami         54   28     32-9  22-19 0.659      34-18      12-4     37-43-2
12 Washington    44   38     22-19 22-19 0.537      33-19      10-6     43-38-1
13 Charlotte     43   39     25-16 18-23 0.524      30-22      6-10     47-32-3
14 Atlanta       38   44     24-17 14-27 0.463      28-24      8-8      38-43-1
15 Orlando       23   59     19-22 4-37  0.280      17-35      4-12     34-45-3
16 Oklahoma City 59   23     34-7  25-16 0.720      36-16      11-5     43-37-2
17 Portland      54   28     31-10 23-18 0.659      31-21      13-3     44-38-0
18 Minnesota     40   42     24-17 16-25 0.488      23-29      7-9      39-43-0
19 Denver        36   46     22-19 14-27 0.439      20-32      5-11     39-43-0
20 Utah          25   57     16-25 9-32  0.305      13-39      4-12     33-43-6
21 L.A. Clippers 57   25     34-7  23-18 0.695      36-16      12-4     46-35-1
22 Golden State  51   31     27-14 24-17 0.622      31-21      11-5     41-38-3
23 Phoenix       48   34     26-15 22-19 0.585      28-24      8-8      52-29-1
24 Sacramento    28   54     17-24 11-30 0.341      15-37      3-13     37-42-3
25 L.A. Lakers   27   55     14-27 13-28 0.329      15-37      6-10     40-40-2
26 San Antonio   62   20     32-9  30-11 0.756      38-14      12-4     45-37-0
27 Houston       54   28     33-8  21-20 0.659      31-21      11-5     40-40-2
28 Memphis       50   32     27-14 23-18 0.610      29-23      4-12     36-43-3
29 Dallas        49   33     26-15 23-18 0.598      29-23      9-7      44-38-0
30 New Orleans   34   48     22-19 12-29 0.415      15-37      4-12     37-39-6
   O_U     ⋯ Div_Losses ATS_Wins ATS_Losses ATS_Tie O_U_Wins O_U_Losses O_U_Tie
1  45-37-0 ⋯ 5          4        3          NA      4        3          NA
2  41-37-4 ⋯ 7          4        4          NA      4        3          NA
3  46-36-0 ⋯ 6          3        4          NA      4        3          NA
4  39-43-0 ⋯ 1          3        4          NA      3        4          NA
5  39-40-3 ⋯ 1          3        4          NA      3        4          NA
6  35-44-3 ⋯ 4          3        4          NA      3        4          NA
7  34-48-0 ⋯ 5          4        4          NA      3        4          NA
8  40-41-1 ⋯ 9          4        4          NA      4        4          NA
9  56-26-0 ⋯ 1          3        4          NA      5        2          NA
10 47-35-0 ⋯ 1          3        4          NA      4        3          NA
11 44-38-0 ⋯ 4          3        4          NA      4        3          NA
12 42-40-0 ⋯ 6          4        3          NA      4        4          NA
13 38-42-2 ⋯ 1          4        3          NA      3        4          NA
14 44-37-1 ⋯ 8          3        4          NA      4        3          NA
15 35-46-1 ⋯ 1          3        4          NA      3        4          NA
16 42-40-0 ⋯ 5          4        3          NA      4        4          NA
17 46-35-1 ⋯ 3          4        3          NA      4        3          NA
18 40-39-3 ⋯ 9          3        4          NA      4        3          NA
19 41-41-0 ⋯ 1          3        4          NA      4        4          NA
20 39-42-1 ⋯ 1          3        4          NA      3        4          NA
21 44-37-1 ⋯ 4          4        3          NA      4        3          NA
22 33-47-2 ⋯ 5          4        3          NA      3        4          NA
23 39-40-3 ⋯ 8          5        2          NA      3        4          NA
24 37-43-2 ⋯ 1          3        4          NA      3        4          NA
25 45-37-0 ⋯ 1          4        4          NA      4        3          NA
26 44-37-1 ⋯ 4          4        3          NA      4        3          NA
27 44-36-2 ⋯ 5          4        4          NA      4        3          NA
28 39-43-0 ⋯ 1          3        4          NA      3        4          NA
29 45-37-0 ⋯ 7          4        3          NA      4        3          NA
30 43-38-1 ⋯ 1          3        3          NA      4        3          NA
   Games_Played Home_Played Away_Played
1  82            3           3
2  82            3           3
3  82            3           3
4  82            3          12
5  82            4          12
6  82            9           4
7  82            3           4
8  82            3           3
9  82            3           3
10 82            4           8
11 82           12           3
12 82            3           3
13 82            3           3
14 82            3           3
15 82            3           7
16 82           10           3
17 82            4           3
18 82            3           3
19 82            3           3
20 82            3          12
21 82           10           3
22 82            3           3
23 82            3           3
24 82            3           4
25 82            3           3
26 82           12           4
27 82           11           4
28 82            3           3
29 82            3           3
30 82            3           3

   Team          Wins Losses Home  Away  Percentage Conference Division ATS
1  New York      54   28     31-10 23-18 0.659      37-15      10-6     46-34-2
2  Brooklyn      49   33     26-15 23-18 0.598      36-16      11-5     39-40-3
3  Boston        41   40     27-13 14-27 0.506      27-24      7-9      36-42-3
4  Philadelphia  34   48     23-18 11-30 0.415      22-30      7-9      39-42-1
5  Toronto       34   48     21-20 13-28 0.415      22-30      5-11     41-40-1
6  Indiana       49   32     30-11 19-21 0.605      31-20      13-3     42-39-0
7  Chicago       45   37     24-17 21-20 0.549      34-18      9-7      36-46-0
8  Milwaukee     38   44     21-20 17-24 0.463      24-28      7-9      37-45-0
9  Detroit       29   53     18-23 11-30 0.354      25-27      8-8      40-41-1
10 Cleveland     24   58     14-27 10-31 0.293      18-34      3-13     39-41-2
11 Miami         66   16     37-4  29-12 0.805      41-11      15-1     46-36-0
12 Atlanta       44   38     25-16 19-22 0.537      29-23      11-5     37-43-2
13 Washington    29   53     22-19 7-34  0.354      15-37      5-11     45-35-2
14 Charlotte     21   61     15-26 6-35  0.256      18-34      6-10     31-50-1
15 Orlando       20   62     12-29 8-33  0.244      10-42      3-13     36-44-2
16 Oklahoma City 60   22     34-7  26-15 0.732      39-13      10-6     49-31-2
17 Denver        57   25     38-3  19-22 0.695      38-14      11-5     49-32-1
18 Utah          43   39     30-11 13-28 0.524      26-26      9-7      42-39-1
19 Portland      33   49     22-19 11-30 0.402      18-34      6-10     34-44-4
20 Minnesota     31   51     20-21 11-30 0.378      17-35      4-12     38-41-3
21 L.A. Clippers 56   26     32-9  24-17 0.683      35-17      11-5     45-37-0
22 Golden State  47   35     28-13 19-22 0.573      28-24      9-7      42-39-1
23 L.A. Lakers   45   37     29-12 16-25 0.549      28-24      8-8      34-46-2
24 Sacramento    28   54     20-21 8-33  0.341      14-38      7-9      38-42-2
25 Phoenix       25   57     17-24 8-33  0.305      17-35      5-11     32-47-3
26 San Antonio   58   24     35-6  23-18 0.707      33-19      12-4     39-41-2
27 Memphis       56   26     32-9  24-17 0.683      34-18      10-6     46-34-2
28 Houston       45   37     29-12 16-25 0.549      24-28      6-10     41-40-1
29 Dallas        41   41     24-17 17-24 0.500      24-28      7-9      48-34-0
30 New Orleans   27   55     16-25 11-30 0.329      15-37      5-11     40-42-0
   O_U     ⋯ Conf_Losses Div_Wins Div_Losses ATS_Wins ATS_Losses O_U_Wins
1  39-41-2 ⋯ 1           1        6          46       34         39
2  41-40-1 ⋯ 1           1        5          39       40         41
3  42-38-1 ⋯ 2           7        9          36       42         42
4  38-41-3 ⋯ 3           7        9          39       42         38
5  42-40-0 ⋯ 3           5        1          41       40         42
6  38-42-1 ⋯ 2           1        3          42       39         38
7  37-44-1 ⋯ 1           9        7          36       46         37
8  39-41-2 ⋯ 2           7        9          37       45         39
9  40-39-3 ⋯ 2           8        8          40       41         40
10 41-41-0 ⋯ 3           3        1          39       41         41
11 42-39-1 ⋯ 1           1        1          46       36         42
12 42-39-1 ⋯ 2           1        5          37       43         42
13 34-45-3 ⋯ 3           5        1          45       35         34
14 38-43-1 ⋯ 3           6        1          31       50         38
15 43-35-4 ⋯ 4           3        1          36       44         43
16 37-43-2 ⋯ 1           1        6          49       31         37
17 46-35-1 ⋯ 1           1        5          49       32         46
18 39-42-1 ⋯ 2           9        7          42       39         39
19 44-36-2 ⋯ 3           6        1          34       44         44
20 37-43-2 ⋯ 3           4        1          38       41         37
21 45-37-0 ⋯ 1           1        5          45       37         45
22 47-34-1 ⋯ 2           9        7          42       39         47
23 42-39-1 ⋯ 2           8        8          34       46         42
24 48-32-2 ⋯ 3           7        9          38       42         48
25 39-42-1 ⋯ 3           5        1          32       47         39
26 36-44-2 ⋯ 1           1        4          39       41         36
27 31-50-1 ⋯ 1           1        6          46       34         31
28 41-41-0 ⋯ 2           6        1          41       40         41
29 47-33-2 ⋯ 2           7        9          48       34         47
30 43-39-0 ⋯ 3           5        1          40       42         43
   O_U_Losses Games_Played Home_Played Away_Played
1  41         82            4           3
2  40         82            3           3
3  38         81            3           3
4  41         82            3           4
5  40         82            4           3
6  42         81            4           3
7  44         82            3           4
8  41         82            4           3
9  39         82            3           4
10 41         82            3           4
11 39         82            7           3
12 39         82            3           3
13 45         82            3          10
14 43         82            3           9
15 35         82            3          11
16 43         82           10           3
17 35         82            6           3
18 42         82            4           3
19 36         82            3           4
20 43         82            4           4
21 37         82           12           3
22 34         82            3           3
23 39         82            3           3
24 32         82            4          11
25 42         82            3          11
26 44         82            9           3
27 50         82           12           3
28 41         82            3           3
29 33         82            3           3
30 39         82            3           4